In [ ]:
import os, re, json, math, time, hashlib, random, warnings
from pathlib import Path
import numpy as np, pandas as pd, cv2
from PIL import Image, ImageOps
import matplotlib.pyplot as plt
warnings.filterwarnings("ignore")
random.seed(42); np.random.seed(42)
print("OpenCV", cv2.__version__)

In [ ]:
# ================================ CONFIG ================================
INPUT_ROOT = Path("/kaggle/input")
OUT = Path("/kaggle/working/objective1"); OUT.mkdir(parents=True, exist_ok=True)
CACHE = OUT / "preprocessed_299"; CACHE.mkdir(exist_ok=True)

CLASSES = ["Melanoma", "BCC", "SCC", "MCC"]
INCLUDE_BENIGN = False
IMG_SIZE = 299

# Leave None to auto-detect a root by name; or hard-set the path.
DS = INPUT_ROOT / "datasets"          # everything is nested under here
DATASET_ROOTS = {
    "ham10000": DS,
    "isic":     DS,
    "dermacon": DS,
    "mcc":      DS,
    "partner":  None,
}

# Keep the heavy image pass tractable: cap how many images per class we analyse
# (MCC is rare, so it is effectively uncapped). Applied AFTER dedupe.
PRE_ANALYZE_CAP = {"Melanoma": 8000, "BCC": 8000, "SCC": 8000, "MCC": 10**9, "Benign": 8000}

DO_PREPROCESS_CACHE = True     # cache DullRazor + resize (needed to reuse for training)
COMPUTE_SKINTONE = True        # ITA-based skin-tone estimation
BLUR_THRESHOLD = 40.0          # Laplacian variance; below this -> rejected as blurry

TARGET_PER_CLASS = 3000        # balance TRAIN up to this via augmentation
MAX_PER_CLASS = 4000           # cap majority classes in TRAIN
VAL_RATIO, TEST_RATIO = 0.15, 0.15
print("Output ->", OUT)

In [ ]:
# ---------- label canonicalization (raw dataset label -> target class) ----------
EXACT_CODE = {"mel":"Melanoma","melanoma":"Melanoma","bcc":"BCC","scc":"SCC","akiec":"SCC",
              "mcc":"MCC","merkel":"MCC","nv":"Benign","bkl":"Benign","df":"Benign","vasc":"Benign"}
SUBSTR_RULES = [("MCC",["merkel"]),("BCC",["basal cell","basal-cell","basalcell"]),
                ("SCC",["squamous cell","squamous-cell","actinic kerat","bowen","intraepiderm","keratoacanth"]),
                ("Melanoma",["melanoma"])]
BENIGN_SUBSTR = ["nevus","nevi","naevus","benign keratos","seborrheic","dermatofibroma",
                 "vascular","angioma","lentigo","dermatitis","psoriasis","eczema","wart"]
CLASS_TO_IDX = {c:i for i,c in enumerate(CLASSES)}

def canonicalize(raw):
    if raw is None or (isinstance(raw,float) and math.isnan(raw)): return None
    s = str(raw).strip().lower(); c = EXACT_CODE.get(s)
    if c is None:
        for cls,keys in SUBSTR_RULES:
            if any(k in s for k in keys): c=cls; break
        if c is None and any(k in s for k in BENIGN_SUBSTR): c="Benign"
    if c=="Benign" and not INCLUDE_BENIGN: return None
    return c if c in CLASS_TO_IDX else None

IMG_EXT = (".jpg",".jpeg",".png",".bmp",".tif",".tiff",".webp")
def list_images(root): return [p for p in Path(root).rglob("*") if p.suffix.lower() in IMG_EXT]
def autodetect_root(*hints):
    if not INPUT_ROOT.exists(): return None
    for child in sorted(INPUT_ROOT.iterdir()):
        if any(h in child.name.lower() for h in hints): return child
    return None
def _pick(df, opts):
    for c in df.columns:
        if c.lower() in opts: return c
    return None

In [ ]:
# ---------------- STEP 2: collect + annotate -> raw manifest ----------------
records = []
def add(src, path, raw, lab, grp): records.append(dict(source=src, path=str(path), raw_label=raw, label=lab, group=grp))

def load_ham():
    root = DATASET_ROOTS["ham10000"] or autodetect_root("ham10000","ham-10000","mnist-ham")
    if not root: print("[HAM10000] skipped"); return
    root=Path(root); meta=next((p for p in root.rglob("*.csv") if "metadata" in p.name.lower()), None)
    if not meta: print("[HAM10000] no metadata csv"); return
    df=pd.read_csv(meta); idx={p.stem:p for p in list_images(root)}; n=0
    for _,r in df.iterrows():
        lab=canonicalize(r.get("dx")); p=idx.get(str(r.get("image_id")))
        if lab and p is not None:
            add("HAM10000", p, r.get("dx"), lab, str(r.get("lesion_id") or r.get("image_id"))); n+=1
    print("[HAM10000]", n)

def load_isic():
    root = DATASET_ROOTS["isic"] or autodetect_root("isic")
    if not root: print("[ISIC] skipped"); return
    root=Path(root); idx={p.stem:p for p in list_images(root)}; n=0; used=False
    for cpath in root.rglob("*.csv"):
        try: df=pd.read_csv(cpath, low_memory=False)
        except Exception: continue
        dcol=_pick(df,("diagnosis","diagnosis_1","dx","benign_malignant","disease")) or next((c for c in df.columns if "diagn" in c.lower()),None)
        idcol=_pick(df,("isic_id","image","image_id","image_name","filename","file","name","id"))
        if not dcol or not idcol: continue
        used=True; pcol=_pick(df,("patient_id","patient","lesion_id"))
        for _,r in df.iterrows():
            lab=canonicalize(r.get(dcol)); 
            if not lab: continue
            key=Path(str(r.get(idcol))).stem; p=idx.get(key)
            if p is None: continue
            grp=str(r.get(pcol)) if (pcol and pd.notna(r.get(pcol))) else key
            add("ISIC", p, r.get(dcol), lab, grp); n+=1
    if not used:
        for p in list_images(root):
            lab=canonicalize(p.parent.name)
            if lab: add("ISIC", p, p.parent.name, lab, p.stem); n+=1
    print("[ISIC]", n)

def load_dermacon():
    root = DATASET_ROOTS["dermacon"] or autodetect_root("dermacon","dermcon","derma-con")
    if not root: print("[DermaCon-IN] skipped"); return
    root=Path(root); idx={p.stem:p for p in list_images(root)}; n=0; used=False
    for cpath in root.rglob("*.csv"):
        try: df=pd.read_csv(cpath, low_memory=False)
        except Exception: continue
        dcol=_pick(df,("diagnosis","diagnosis_1","disease","label","class")) or next((c for c in df.columns if "diagn" in c.lower()),None)
        idcol=_pick(df,("image","image_id","filename","file","name","id","image_name"))
        if not dcol or not idcol: continue
        used=True
        for _,r in df.iterrows():
            lab=canonicalize(r.get(dcol)); p=idx.get(Path(str(r.get(idcol))).stem)
            if lab and p is not None: add("DermaCon-IN", p, r.get(dcol), lab, p.stem); n+=1
    if not used:
        for p in list_images(root):
            lab=canonicalize(p.parent.name)
            if lab: add("DermaCon-IN", p, p.parent.name, lab, p.stem); n+=1
    print("[DermaCon-IN]", n, "(South-Asian skin tones)")

def load_mcc():
    root = DATASET_ROOTS["mcc"] or autodetect_root("mcc","merkel")
    if not root: print("[MCC] skipped"); return
    n=0
    for p in list_images(root):
        pn=p.parent.name.lower()
        lab = ("Benign" if INCLUDE_BENIGN else None) if any(k in pn for k in ("neg","normal","benign","non")) else "MCC"
        if lab: add("MCC-Dataset", p, p.parent.name, lab, p.stem); n+=1
    print("[MCC]", n)

def load_partner():
    root = DATASET_ROOTS["partner"] or autodetect_root("partner","clinic")
    if not root: print("[Partner clinic] none attached (optional)"); return
    n=0
    for p in list_images(root):
        lab=canonicalize(p.parent.name)
        if lab: add("PartnerClinic", p, p.parent.name, lab, p.stem); n+=1
    print("[Partner clinic]", n)

for fn in (load_ham, load_isic, load_dermacon, load_mcc, load_partner):
    try: fn()
    except Exception as e: print("  !!", fn.__name__, e)

raw = pd.DataFrame(records)
assert len(raw)>0, "No images mapped. Confirm datasets are attached."
print("\nRaw annotated images:", len(raw))
print(raw.groupby(["label","source"]).size().unstack(fill_value=0))

In [ ]:
# ---------------- STEP 3a: de-duplicate (exact bytes, MD5) ----------------
def md5(path, chunk=1<<20):
    h=hashlib.md5()
    try:
        with open(path,"rb") as f:
            for b in iter(lambda: f.read(chunk), b""): h.update(b)
        return h.hexdigest()
    except Exception:
        return None
raw["md5"]=raw["path"].map(md5)
before=len(raw)
raw=raw[raw["md5"].notna()].drop_duplicates(subset="md5").reset_index(drop=True)
print(f"Removed {before-len(raw)} exact-duplicate/corrupt files; {len(raw)} remain")

# cap per class before the heavy image pass (keeps runtime tractable; MCC uncapped)
parts=[]
for c,sub in raw.groupby("label"):
    parts.append(sub.sample(min(len(sub), PRE_ANALYZE_CAP.get(c,10**9)), random_state=42))
raw=pd.concat(parts).sample(frac=1, random_state=42).reset_index(drop=True)
print("After per-class analyse cap:", len(raw), dict(raw["label"].value_counts()))

In [ ]:
# ---------------- STEP 4+5: skin tone (ITA), blur QC, preprocess cache ----------------
def dull_razor(bgr):
    gray=cv2.cvtColor(bgr,cv2.COLOR_BGR2GRAY)
    k=cv2.getStructuringElement(cv2.MORPH_CROSS,(9,9))
    bh=cv2.morphologyEx(gray,cv2.MORPH_BLACKHAT,k)
    _,mask=cv2.threshold(bh,10,255,cv2.THRESH_BINARY)
    return cv2.inpaint(bgr,mask,1,cv2.INPAINT_TELEA)

def estimate_ita(rgb):
    # ITA(deg) = arctan((L*-50)/b*) on healthy border skin (lesion assumed central).
    h,w=rgb.shape[:2]; lab=cv2.cvtColor(rgb,cv2.COLOR_RGB2Lab).astype(np.float32)
    L=lab[...,0]*100.0/255.0; b=lab[...,2]-128.0; Lraw=lab[...,0]
    m=max(4,int(0.12*min(h,w))); ring=np.zeros((h,w),bool)
    ring[:m,:]=True; ring[-m:,:]=True; ring[:,:m]=True; ring[:,-m:]=True
    skin=ring & (Lraw>40) & (Lraw<245)              # drop hair (dark) & specular (bright)
    if skin.sum()<50: skin=(Lraw>40)&(Lraw<245)
    if skin.sum()<10: return float("nan")
    return float(np.degrees(np.arctan2(np.median(L[skin])-50.0, np.median(b[skin])+1e-6)))

def ita_band(ita):
    if np.isnan(ita): return "Unknown"
    if ita>55: return "Very light (I)"
    if ita>41: return "Light (II)"
    if ita>28: return "Intermediate (III)"
    if ita>10: return "Tan (IV)"
    if ita>-30: return "Brown (V)"
    return "Dark (VI)"

def cache_path_for(p): return CACHE/(re.sub(r"[^A-Za-z0-9]+","_",str(p))[-120:]+".npy")

blur_l, ita_l, ok_l = [], [], []
t0=time.time()
for i,p in enumerate(raw["path"].tolist()):
    try:
        pil=ImageOps.exif_transpose(Image.open(p).convert("RGB")); rgb=np.array(pil)
    except Exception:
        blur_l.append(np.nan); ita_l.append(np.nan); ok_l.append(False); continue
    gray=cv2.cvtColor(rgb,cv2.COLOR_RGB2GRAY)
    blur_l.append(float(cv2.Laplacian(gray,cv2.CV_64F).var()))
    ita_l.append(estimate_ita(rgb) if COMPUTE_SKINTONE else np.nan)
    if DO_PREPROCESS_CACHE:
        bgr=dull_razor(cv2.cvtColor(rgb,cv2.COLOR_RGB2BGR))
        bgr=cv2.resize(bgr,(IMG_SIZE,IMG_SIZE),interpolation=cv2.INTER_CUBIC)
        np.save(cache_path_for(p), cv2.cvtColor(bgr,cv2.COLOR_BGR2RGB))
    ok_l.append(True)
    if i%2000==0: print(f"  {i}/{len(raw)}  ({time.time()-t0:.0f}s)")
raw["blur"]=blur_l; raw["ita"]=ita_l; raw["ok"]=ok_l
raw["skin_band"]=raw["ita"].map(ita_band)

corrupt=(~raw["ok"]).sum(); blurry=((raw["ok"]) & (raw["blur"]<BLUR_THRESHOLD)).sum()
raw=raw[(raw["ok"]) & (raw["blur"]>=BLUR_THRESHOLD)].reset_index(drop=True)
print(f"\nQC: dropped {corrupt} corrupt + {blurry} blurry -> {len(raw)} clean images")
print("done in", round(time.time()-t0), "s")

In [ ]:
# ---------------- STEP 6a: leakage-safe grouped split ----------------
from sklearn.model_selection import StratifiedGroupKFold, GroupShuffleSplit
def grouped_split(frame, val_ratio, test_ratio, seed=42):
    y=frame["label"].map(CLASS_TO_IDX).values; g=frame["group"].values
    try:
        s=StratifiedGroupKFold(n_splits=max(2,round(1/test_ratio)),shuffle=True,random_state=seed)
        tr,te=next(s.split(frame,y,g)); a,b=frame.iloc[tr].copy(),frame.iloc[te].copy()
        s2=StratifiedGroupKFold(n_splits=max(2,round(1/(val_ratio/(1-test_ratio)))),shuffle=True,random_state=seed)
        x,v=next(s2.split(a,a["label"].map(CLASS_TO_IDX).values,a["group"].values))
        return a.iloc[x].copy(), a.iloc[v].copy(), b
    except Exception as e:
        print("fallback GroupShuffleSplit:",e)
        gss=GroupShuffleSplit(1,test_size=test_ratio,random_state=seed); tr,te=next(gss.split(frame,y,g))
        a,b=frame.iloc[tr].copy(),frame.iloc[te].copy()
        g2=GroupShuffleSplit(1,test_size=val_ratio/(1-test_ratio),random_state=seed); x,v=next(g2.split(a,a["label"],a["group"]))
        return a.iloc[x].copy(), a.iloc[v].copy(), b

df_train, df_val, df_test = grouped_split(raw, VAL_RATIO, TEST_RATIO)
for d,n in [(df_train,"train"),(df_val,"val"),(df_test,"test")]: d["split"]=n
print("sizes:", len(df_train), len(df_val), len(df_test))

In [1]:
from pathlib import Path

datasets = [
    "/kaggle/input/datasets/abhig888/dermacon-in",
    "/kaggle/input/datasets/hiro002/dermacon-in-dataset",
    "/kaggle/input/datasets/riyaelizashaju/isic-skin-disease-image-dataset-labelled",
    "/kaggle/input/datasets/quantumcoders05/mcc-dataset",
    "/kaggle/input/datasets/nodoubttome/skin-cancer9-classesisic",
    "/kaggle/input/datasets/kmader/skin-cancer-mnist-ham10000",
    "/kaggle/input/datasets/ahmedxc4/skin-ds",
    "/kaggle/input/datasets/tomooinubushi/all-isic-data-20240629"
]

for d in datasets:
    print("\n" + "="*80)
    print(d)

    root = Path(d)

    if not root.exists():
        print("❌ NOT FOUND")
        continue

    for item in sorted(root.iterdir()):
        if item.is_dir():
            print("📁", item.name)
        else:
            print("📄", item.name)

================================================================================
/kaggle/input/datasets/abhig888/dermacon-in
📁 DATASET
📄 Infer_CBM_MC.ipynb
📄 Infer_Swin_MC.ipynb
📁 METADATA
📄 Metadata_schema.md
📄 README.md
📁 checkpoints
📄 train_CBM_SC_MC_type1.py
📄 train_CBM_SC_MC_type2.py
📄 train_cbm_mc.py
📄 train_swin_mc.py

================================================================================
/kaggle/input/datasets/hiro002/dermacon-in-dataset
📁 DATASET
📄 Infer_CBM_MC.ipynb
📄 Infer_Swin_MC.ipynb
📁 METADATA
📄 Metadata_schema.md
📄 README.md
📁 checkpoints
📄 train_CBM_SC_MC_type1.py
📄 train_CBM_SC_MC_type2.py
📄 train_cbm_mc.py
📄 train_swin_mc.py

================================================================================
/kaggle/input/datasets/riyaelizashaju/isic-skin-disease-image-dataset-labelled
📁 ISIC_Labelled

================================================================================
/kaggle/input/datasets/quantumcoders05/mcc-dataset
❌ NOT FOUND

================================================================================
/kaggle/input/datasets/nodoubttome/skin-cancer9-classesisic
📁 Skin cancer ISIC The International Skin Imaging Collaboration
📁 skin cancer isic the international skin imaging collaboration

================================================================================
/kaggle/input/datasets/kmader/skin-cancer-mnist-ham10000
📁 HAM10000_images_part_1
📁 HAM10000_images_part_2
📄 HAM10000_metadata.csv
📁 ham10000_images_part_1
📁 ham10000_images_part_2
📄 hmnist_28_28_L.csv
📄 hmnist_28_28_RGB.csv
📄 hmnist_8_8_L.csv
📄 hmnist_8_8_RGB.csv

================================================================================
/kaggle/input/datasets/ahmedxc4/skin-ds
📄 README.md
📁 test
📁 train
📁 val

================================================================================
/kaggle/input/datasets/tomooinubushi/all-isic-data-20240629
📄 attribution.txt
📄 image.hdf5
📄 image_256sq.hdf5
📁 images
📁 licenses
📄 metadata.csv

In [2]:
from pathlib import Path

# Dataset roots that were found
dataset_roots = {
    "dermacon_1": Path("/kaggle/input/datasets/abhig888/dermacon-in"),
    "dermacon_2": Path("/kaggle/input/datasets/hiro002/dermacon-in-dataset"),
    "isic_labelled": Path("/kaggle/input/datasets/riyaelizashaju/isic-skin-disease-image-dataset-labelled"),
    "isic_9class": Path("/kaggle/input/datasets/nodoubttome/skin-cancer9-classesisic"),
    "ham10000": Path("/kaggle/input/datasets/kmader/skin-cancer-mnist-ham10000"),
    "skin_ds": Path("/kaggle/input/datasets/ahmedxc4/skin-ds"),
    "all_isic": Path("/kaggle/input/datasets/tomooinubushi/all-isic-data-20240629"),
}

# File extensions we care about
image_ext = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
data_ext = {".csv", ".json", ".txt", ".xlsx"}

for name, root in dataset_roots.items():

    print("\n" + "=" * 90)
    print(f"DATASET: {name}")
    print(f"PATH:    {root}")

    if not root.exists():
        print("STATUS: NOT FOUND")
        continue

    image_count = 0
    data_files = []

    # Look through files safely
    for file in root.rglob("*"):

        if not file.is_file():
            continue

        if file.suffix.lower() in image_ext:
            image_count += 1

        elif file.suffix.lower() in data_ext:
            data_files.append(file)

    print(f"IMAGE COUNT: {image_count}")

    print("\nDATA / METADATA FILES:")
    if data_files:
        for file in sorted(data_files)[:30]:
            print("  ", file.relative_to(root))
    else:
        print("   None found")

    print("\nTOP-LEVEL FOLDERS:")
    folders = [x for x in root.iterdir() if x.is_dir()]

    if folders:
        for folder in sorted(folders):
            print("  📁", folder.name)
    else:
        print("   None")

==========================================================================================
DATASET: dermacon_1
PATH:    /kaggle/input/datasets/abhig888/dermacon-in
IMAGE COUNT: 5450

DATA / METADATA FILES:
   METADATA/Skin_Metadata-1.csv
   METADATA/test_split-1.csv
   METADATA/train_split-1.csv

TOP-LEVEL FOLDERS:
  📁 DATASET
  📁 METADATA
  📁 checkpoints

==========================================================================================
DATASET: dermacon_2
PATH:    /kaggle/input/datasets/hiro002/dermacon-in-dataset
IMAGE COUNT: 5450

DATA / METADATA FILES:
   METADATA/Skin_Metadata.csv
   METADATA/test_split.csv
   METADATA/train_split.csv

TOP-LEVEL FOLDERS:
  📁 DATASET
  📁 METADATA
  📁 checkpoints

==========================================================================================
DATASET: isic_labelled
PATH:    /kaggle/input/datasets/riyaelizashaju/isic-skin-disease-image-dataset-labelled

KeyboardInterrupt:

In [3]:
from pathlib import Path

root = Path("/kaggle/input/datasets/abhig888/dermacon-in")

print("DATASET:", root)
print("\nInside dataset:\n")

for item in sorted(root.iterdir()):
    if item.is_dir():
        print("📁", item.name)
    else:
        print("📄", item.name)

DATASET: /kaggle/input/datasets/abhig888/dermacon-in

Inside dataset:

📁 DATASET
📄 Infer_CBM_MC.ipynb
📄 Infer_Swin_MC.ipynb
📁 METADATA
📄 Metadata_schema.md
📄 README.md
📁 checkpoints
📄 train_CBM_SC_MC_type1.py
📄 train_CBM_SC_MC_type2.py
📄 train_cbm_mc.py
📄 train_swin_mc.py

In [4]:
from pathlib import Path

root = Path("/kaggle/input/datasets/abhig888/dermacon-in/DATASET")

print("DATASET FOLDER:", root)
print("\nInside DATASET:\n")

for item in sorted(root.iterdir()):
    if item.is_dir():
        print("📁", item.name)
    else:
        print("📄", item.name)

DATASET FOLDER: /kaggle/input/datasets/abhig888/dermacon-in/DATASET

Inside DATASET:

📁 DATASET_0
📁 DATASET_1

In [1]:
from pathlib import Path

root = Path("/kaggle/input/datasets/abhig888/dermacon-in/DATASET")

print("DATASET FOLDER:", root)
print("\nInside DATASET:\n")

for item in sorted(root.iterdir()):
    if item.is_dir():
        print("📁", item.name)
    else:
        print("📄", item.name)

DATASET FOLDER: /kaggle/input/datasets/abhig888/dermacon-in/DATASET

Inside DATASET:

📁 DATASET_0
📁 DATASET_1

In [2]:
from pathlib import Path

root = Path("/kaggle/input/datasets/abhig888/dermacon-in/DATASET/DATASET_0")

print("DATASET_0:", root)
print("\nInside DATASET_0:\n")

for item in sorted(root.iterdir()):
    if item.is_dir():
        print("📁", item.name)
    else:
        print("📄", item.name)

DATASET_0: /kaggle/input/datasets/abhig888/dermacon-in/DATASET/DATASET_0

Inside DATASET_0:

📁 DATASET_0

In [3]:
from pathlib import Path

root = Path("/kaggle/input/datasets/abhig888/dermacon-in/DATASET/DATASET_0/DATASET_0")

print("INNER DATASET_0:", root)
print("\nInside INNER DATASET_0:\n")

for item in sorted(root.iterdir()):
    if item.is_dir():
        print("📁", item.name)
    else:
        print("📄", item.name)

INNER DATASET_0: /kaggle/input/datasets/abhig888/dermacon-in/DATASET/DATASET_0/DATASET_0

Inside INNER DATASET_0:

📄 IMG_0002.jpg
📄 IMG_0005.jpg
📄 IMG_0009.jpg
📄 IMG_0010.jpg
📄 IMG_0011.jpg
📄 IMG_0015.jpg
📄 IMG_0017.jpg
📄 IMG_0019.jpg
📄 IMG_0031.jpg
📄 IMG_0033.jpg
📄 IMG_0034.jpg
📄 IMG_0036.jpg
📄 IMG_0040.jpg
📄 IMG_0044.jpg
📄 IMG_0045.jpg
📄 IMG_0048.jpg
📄 IMG_0051.jpg
📄 IMG_0053.jpg
📄 IMG_0055.jpg
📄 IMG_0056.jpg
📄 IMG_0057.jpg
📄 IMG_0058.jpg
📄 IMG_0060.jpg
📄 IMG_0063.jpg
📄 IMG_0064.jpg
📄 IMG_0065.jpg
📄 IMG_0068.jpg
📄 IMG_0072.jpg
📄 IMG_0073.jpg
📄 IMG_0075.jpg
📄 IMG_0077.jpg
📄 IMG_0079.jpg
📄 IMG_0081.jpg
📄 IMG_0082.jpg
📄 IMG_0083.jpg
📄 IMG_0084.jpg
📄 IMG_0087.jpg
📄 IMG_0089.jpg
📄 IMG_0090.jpg
📄 IMG_0096.jpg
📄 IMG_0097.jpg
📄 IMG_0101.jpg
📄 IMG_0102.jpg
📄 IMG_0103.jpg
📄 IMG_0104.jpg
📄 IMG_0108.jpg
📄 IMG_0109.jpg
📄 IMG_0110.jpg
📄 IMG_0111.jpg
📄 IMG_0114.jpg
📄 IMG_0115.jpg
📄 IMG_0117.jpg
📄 IMG_0120.jpg
📄 IMG_0123.jpg
📄 IMG_0125.jpg
📄 IMG_0126.jpg
📄 IMG_0127.jpg
📄 IMG_0129.jpg
📄 IMG_0131.jpg
📄 IMG_0133.jpg
📄 IMG_0134.jpg
📄 IMG_0138.jpg
📄 IMG_0139.jpg
📄 IMG_0140.jpg
📄 IMG_0141.jpg
📄 IMG_0142.jpg
📄 IMG_0144.jpg
📄 IMG_0146.jpg
📄 IMG_0148.jpg
📄 IMG_0155.jpg
📄 IMG_0156.jpg
📄 IMG_0157.jpg
📄 IMG_0158.jpg
📄 IMG_0161.jpg
📄 IMG_0162.jpg
📄 IMG_0163.jpg
📄 IMG_0166.jpg
📄 IMG_0168.jpg
📄 IMG_0169.jpg
📄 IMG_0170.jpg
📄 IMG_0171.jpg
📄 IMG_0172.jpg
📄 IMG_0173.jpg
📄 IMG_0174.jpg
📄 IMG_0175.jpg
📄 IMG_0176.jpg
📄 IMG_0178.jpg
📄 IMG_0179.jpg
📄 IMG_0180.jpg
📄 IMG_0182.jpg
📄 IMG_0183.jpg
📄 IMG_0185.jpg
📄 IMG_0186.jpg
📄 IMG_0192.jpg
📄 IMG_0194.jpg
📄 IMG_0195.jpg
📄 IMG_0196.jpg
📄 IMG_0199.jpg
📄 IMG_0200.jpg
📄 IMG_0202.jpg
📄 IMG_0203.jpg
📄 IMG_0204.jpg
📄 IMG_0208.jpg
📄 IMG_0210.jpg
📄 IMG_0211.jpg
📄 IMG_0214.jpg
📄 IMG_0215.jpg
📄 IMG_0217.jpg
📄 IMG_0218.jpg
📄 IMG_0220.jpg
📄 IMG_0223.jpg
📄 IMG_0227.jpg
📄 IMG_0228.jpg
📄 IMG_0229.jpg
📄 IMG_0231.jpg
📄 IMG_0232.jpg
📄 IMG_0234.jpg
📄 IMG_0236.jpg
📄 IMG_0238.jpg
📄 IMG_0242.jpg
📄 IMG_0243_2.jpg
📄 IMG_0244.jpg
📄 IMG_0245.jpg
📄 IMG_0248.jpg
📄 IMG_0249.jpg
📄 IMG_0250.jpg
📄 IMG_0251.jpg
📄 IMG_0254.jpg
📄 IMG_0256.jpg
📄 IMG_0257.jpg
📄 IMG_0260.jpg
📄 IMG_0263.jpg
📄 IMG_0267.jpg
📄 IMG_0269.jpg
📄 IMG_0271.jpg
📄 IMG_0277.jpg
📄 IMG_0281.jpg
📄 IMG_0287.jpg
📄 IMG_0289.jpg
📄 IMG_0292.jpg
📄 IMG_0296.jpg
📄 IMG_0297.jpg
📄 IMG_0299.jpg
📄 IMG_0304.jpg
📄 IMG_0311.jpg
📄 IMG_0313.jpg
📄 IMG_0314.jpg
📄 IMG_0317.jpg
📄 IMG_0318.jpg
📄 IMG_0320.jpg
📄 IMG_0323.jpg
📄 IMG_0325.jpg
📄 IMG_0327.jpg
📄 IMG_0335.jpg
📄 IMG_0339.jpg
📄 IMG_0341.jpg
📄 IMG_0345.jpg
📄 IMG_0346.jpg
📄 IMG_0347.jpg
📄 IMG_0349.jpg
📄 IMG_0350.jpg
📄 IMG_0378.jpg
📄 IMG_0379.jpg
📄 IMG_0381.jpg
📄 IMG_0384.jpg
📄 IMG_0386.jpg
📄 IMG_0388.jpg
📄 IMG_0390.jpg
📄 IMG_0394.jpg
📄 IMG_0397.jpg
📄 IMG_0399.jpg
📄 IMG_0403.jpg
📄 IMG_0405.jpg
📄 IMG_0408.jpg
📄 IMG_0409.jpg
📄 IMG_0410.jpg
📄 IMG_0411.jpg
📄 IMG_0412.jpg
📄 IMG_0414.jpg
📄 IMG_0419.jpg
📄 IMG_0420.jpg
📄 IMG_0427.jpg
📄 IMG_0429.jpg
📄 IMG_0430.jpg
📄 IMG_0431.jpg
📄 IMG_0433.jpg
📄 IMG_0434_1.jpg
📄 IMG_0434_2.jpg
📄 IMG_0441.jpg
📄 IMG_0443.jpg
📄 IMG_0444.jpg
📄 IMG_0446.jpg
📄 IMG_0447.jpg
📄 IMG_0448.jpg
📄 IMG_0450.jpg
📄 IMG_0451.jpg
📄 IMG_0453.jpg
📄 IMG_0466.jpg
📄 IMG_0476.jpg
📄 IMG_0477.jpg
📄 IMG_0478.jpg
📄 IMG_0479.jpg
📄 IMG_0483.jpg
📄 IMG_0484.jpg
📄 IMG_0485.jpg
📄 IMG_0487.jpg
📄 IMG_0488_1.jpg
📄 IMG_0488_2.jpg
📄 IMG_0490_1.jpg
📄 IMG_0491_1.jpg
📄 IMG_0493.jpg
📄 IMG_0494.jpg
📄 IMG_0495.jpg
📄 IMG_0496.jpg
📄 IMG_0500_1.jpg
📄 IMG_0500_2.jpg
📄 IMG_0501_1.jpg
📄 IMG_0502_1.jpg
📄 IMG_0503.jpg
📄 IMG_0504.jpg
📄 IMG_0508.jpg
📄 IMG_0509.jpg
📄 IMG_0511.jpg
📄 IMG_0512_1.jpg
📄 IMG_0513.jpg
📄 IMG_0515.jpg
📄 IMG_0522.jpg
📄 IMG_0527.jpg
📄 IMG_0529.jpg
📄 IMG_0530.jpg
📄 IMG_0534.jpg
📄 IMG_0537.jpg
📄 IMG_0538.jpg
📄 IMG_0539.jpg
📄 IMG_0540.jpg
📄 IMG_0543.jpg
📄 IMG_0544.jpg
📄 IMG_0545.jpg
📄 IMG_0548.jpg
📄 IMG_0549.jpg
📄 IMG_0550.jpg
📄 IMG_0554.jpg
📄 IMG_0555.jpg
📄 IMG_0557.jpg
📄 IMG_0561.jpg
📄 IMG_0563.jpg
📄 IMG_0568.jpg
📄 IMG_0571.jpg
📄 IMG_0572.jpg
📄 IMG_0576.jpg
📄 IMG_0577.jpg
📄 IMG_0578.jpg
📄 IMG_0580.jpg
📄 IMG_0597.jpg
📄 IMG_0605.jpg
📄 IMG_0607.jpg
📄 IMG_0609.jpg
📄 IMG_0610.jpg
📄 IMG_0612.jpg
📄 IMG_0614.jpg
📄 IMG_0615.jpg
📄 IMG_0616.jpg
📄 IMG_0618.jpg
📄 IMG_0620.jpg
📄 IMG_0621.jpg
📄 IMG_0622.jpg
📄 IMG_0623.jpg
📄 IMG_0624.jpg
📄 IMG_0626.jpg
📄 IMG_0629.jpg
📄 IMG_0631.jpg
📄 IMG_0633.jpg
📄 IMG_0635.jpg
📄 IMG_0639.jpg
📄 IMG_0643.jpg
📄 IMG_0646.jpg
📄 IMG_0647.jpg
📄 IMG_0648.jpg
📄 IMG_0649.jpg
📄 IMG_0650.jpg
📄 IMG_0652.jpg
📄 IMG_0653.jpg
📄 IMG_0654.jpg
📄 IMG_0656.jpg
📄 IMG_0659.jpg
📄 IMG_0662.jpg
📄 IMG_0663.jpg
📄 IMG_0665.jpg
📄 IMG_0667.jpg
📄 IMG_0674.jpg
📄 IMG_0675.jpg
📄 IMG_0677.jpg
📄 IMG_0678.jpg
📄 IMG_0682.jpg
📄 IMG_0682_1.jpg
📄 IMG_0685.jpg
📄 IMG_0686.jpg
📄 IMG_0687.jpg
📄 IMG_0688.jpg
📄 IMG_0689.jpg
📄 IMG_0690.jpg
📄 IMG_0691.jpg
📄 IMG_0695.jpg
📄 IMG_0696.jpg
📄 IMG_0700.jpg
📄 IMG_0706.jpg
📄 IMG_0709.jpg
📄 IMG_0715.jpg
📄 IMG_0717.jpg
📄 IMG_0718.jpg
📄 IMG_0721.jpg
📄 IMG_0722.jpg
📄 IMG_0724.jpg
📄 IMG_0727.jpg
📄 IMG_0749.jpg
📄 IMG_0751.jpg
📄 IMG_0753.jpg
📄 IMG_0754.jpg
📄 IMG_0756.jpg
📄 IMG_0763.jpg
📄 IMG_0766.jpg
📄 IMG_0767.jpg
📄 IMG_0768.jpg
📄 IMG_0770.jpg
📄 IMG_0771.jpg
📄 IMG_0773.jpg
📄 IMG_0775.jpg
📄 IMG_0776.jpg
📄 IMG_0777.jpg
📄 IMG_0779.jpg
📄 IMG_0781.jpg
📄 IMG_0782.jpg
📄 IMG_0784.jpg
📄 IMG_0785.jpg
📄 IMG_0787.jpg
📄 IMG_0789.jpg
📄 IMG_0790.jpg
📄 IMG_0792.jpg
📄 IMG_0793.jpg
📄 IMG_0795.jpg
📄 IMG_0799.jpg
📄 IMG_0803.jpg
📄 IMG_0806.jpg
📄 IMG_0807.jpg
📄 IMG_0810.jpg
📄 IMG_0814.jpg
📄 IMG_0815.jpg
📄 IMG_0818.jpg
📄 IMG_0819.jpg
📄 IMG_0820.jpg
📄 IMG_0821.jpg
📄 IMG_0823.jpg
📄 IMG_0825.jpg
📄 IMG_0826.jpg
📄 IMG_0827.jpg
📄 IMG_0829.jpg
📄 IMG_0830.jpg
📄 IMG_0832.jpg
📄 IMG_0834.jpg
📄 IMG_0836.jpg
📄 IMG_0837.jpg
📄 IMG_0844.jpg
📄 IMG_0846.jpg
📄 IMG_0847.jpg
📄 IMG_0848.jpg
📄 IMG_0849.jpg
📄 IMG_0850.jpg
📄 IMG_0853.jpg
📄 IMG_0855.jpg
📄 IMG_0860.jpg
📄 IMG_0865.jpg
📄 IMG_0866.jpg
📄 IMG_0869.jpg
📄 IMG_0870.jpg
📄 IMG_0873.jpg
📄 IMG_0874.jpg
📄 IMG_0876.jpg
📄 IMG_0878.jpg
📄 IMG_0879.jpg
📄 IMG_0880.jpg
📄 IMG_0885.jpg
📄 IMG_0890.jpg
📄 IMG_0896.jpg
📄 IMG_0899.jpg
📄 IMG_0902.jpg
📄 IMG_0904.jpg
📄 IMG_0906.jpg
📄 IMG_0908.jpg
📄 IMG_0911.jpg
📄 IMG_0912.jpg
📄 IMG_0916.jpg
📄 IMG_0917.jpg
📄 IMG_0918.jpg
📄 IMG_0921.jpg
📄 IMG_0928.jpg
📄 IMG_0929.jpg
📄 IMG_0931.jpg
📄 IMG_0933.jpg
📄 IMG_0934.jpg
📄 IMG_0936.jpg
📄 IMG_0937.jpg
📄 IMG_0940.jpg
📄 IMG_0941.jpg
📄 IMG_0942.jpg
📄 IMG_0943.jpg
📄 IMG_0944.jpg
📄 IMG_0945.jpg
📄 IMG_0946.jpg
📄 IMG_0947.jpg
📄 IMG_0948.jpg
📄 IMG_0949.jpg
📄 IMG_0950.jpg
📄 IMG_0952.jpg
📄 IMG_0954.jpg
📄 IMG_0957.jpg
📄 IMG_0958.jpg
📄 IMG_0959.jpg
📄 IMG_0960.jpg
📄 IMG_0961.jpg
📄 IMG_0962.jpg
📄 IMG_0963.jpg
📄 IMG_0966.jpg
📄 IMG_0968.jpg
📄 IMG_0971.jpg
📄 IMG_0973.jpg
📄 IMG_0974.jpg
📄 IMG_0978.jpg
📄 IMG_0979.jpg
📄 IMG_0982.jpg
📄 IMG_0984.jpg
📄 IMG_0987.jpg
📄 IMG_0989.jpg
📄 IMG_0991.jpg
📄 IMG_0992.jpg
📄 IMG_0994.jpg
📄 IMG_0996.jpg
📄 IMG_1001.jpg
📄 IMG_1002.jpg
📄 IMG_1005_1.jpg
📄 IMG_1006.jpg
📄 IMG_1007.jpg
📄 IMG_1010.jpg
📄 IMG_1015.jpg
📄 IMG_1018.jpg
📄 IMG_1019.jpg
📄 IMG_1021.jpg
📄 IMG_1022.jpg
📄 IMG_1024.jpg
📄 IMG_1027.jpg
📄 IMG_1030.jpg
📄 IMG_1032.jpg
📄 IMG_1034.jpg
📄 IMG_1040.jpg
📄 IMG_1041.jpg
📄 IMG_1043.jpg
📄 IMG_1044.jpg
📄 IMG_1046.jpg
📄 IMG_1049.jpg
📄 IMG_1050.jpg
📄 IMG_1052.jpg
📄 IMG_1054.jpg
📄 IMG_1056.jpg
📄 IMG_1057.jpg
📄 IMG_1062.jpg
📄 IMG_1064.jpg
📄 IMG_1065.jpg
📄 IMG_1066.jpg
📄 IMG_1069.jpg
📄 IMG_1071.jpg
📄 IMG_1073.jpg
📄 IMG_1075.jpg
📄 IMG_1076.jpg
📄 IMG_1077.jpg
📄 IMG_1078.jpg
📄 IMG_1079.jpg
📄 IMG_1081.jpg
📄 IMG_1085.jpg
📄 IMG_1088.jpg
📄 IMG_1090.jpg
📄 IMG_1092.jpg
📄 IMG_1093.jpg
📄 IMG_1094.jpg
📄 IMG_1097_1.jpg
📄 IMG_1098_1.jpg
📄 IMG_1100.jpg
📄 IMG_1102.jpg
📄 IMG_1105.jpg
📄 IMG_1108.jpg
📄 IMG_1109.jpg
📄 IMG_1110.jpg
📄 IMG_1111.jpg
📄 IMG_1113.jpg
📄 IMG_1114.jpg
📄 IMG_1115.jpg
📄 IMG_1116.jpg
📄 IMG_1117.jpg
📄 IMG_1124.jpg
📄 IMG_1126.jpg
📄 IMG_1129.jpg
📄 IMG_1130.jpg
📄 IMG_1133.jpg
📄 IMG_1140.jpg
📄 IMG_1142.jpg
📄 IMG_1143.jpg
📄 IMG_1145.jpg
📄 IMG_1146.jpg
📄 IMG_1151.jpg
📄 IMG_1152.jpg
📄 IMG_1155.jpg
📄 IMG_1157.jpg
📄 IMG_1159.jpg
📄 IMG_1164.jpg
📄 IMG_1166.jpg
📄 IMG_1168.jpg
📄 IMG_1169.jpg
📄 IMG_1171.jpg
📄 IMG_1175.jpg
📄 IMG_1177.jpg
📄 IMG_1180.jpg
📄 IMG_1182.jpg
📄 IMG_1184.jpg
📄 IMG_1186.jpg
📄 IMG_1188.jpg
📄 IMG_1196.jpg
📄 IMG_1198.jpg
📄 IMG_1202.jpg
📄 IMG_1204.jpg
📄 IMG_1215.jpg
📄 IMG_1219.jpg
📄 IMG_1221.jpg
📄 IMG_1226.jpg
📄 IMG_1228.jpg
📄 IMG_1231_1.jpg
📄 IMG_1233.jpg
📄 IMG_1234.jpg
📄 IMG_1239.jpg
📄 IMG_1240_1.jpg
📄 IMG_1242.jpg
📄 IMG_1246_1.jpg
📄 IMG_1250.jpg
📄 IMG_1257.jpg
📄 IMG_1262.jpg
📄 IMG_1263.jpg
📄 IMG_1264_1.jpg
📄 IMG_1272.jpg
📄 IMG_1273.jpg
📄 IMG_1279.jpg
📄 IMG_1280_1.jpg
📄 IMG_1281.jpg
📄 IMG_1283.jpg
📄 IMG_1284_1.jpg
📄 IMG_1285.jpg
📄 IMG_1286.jpg
📄 IMG_1290.jpg
📄 IMG_1291.jpg
📄 IMG_1292_1.jpg
📄 IMG_1293.jpg
📄 IMG_1294.jpg
📄 IMG_1295.jpg
📄 IMG_1296.jpg
📄 IMG_1297.jpg
📄 IMG_1298.jpg
📄 IMG_1302.jpg
📄 IMG_1303.jpg
📄 IMG_1306.jpg
📄 IMG_1307.jpg
📄 IMG_1309_1.jpg
📄 IMG_1314.jpg
📄 IMG_1317.jpg
📄 IMG_1318_1.jpg
📄 IMG_1322.jpg
📄 IMG_1323.jpg
📄 IMG_1324.jpg
📄 IMG_1325.jpg
📄 IMG_1326_1.jpg
📄 IMG_1328.jpg
📄 IMG_1329.jpg
📄 IMG_1335.jpg
📄 IMG_1338_1.jpg
📄 IMG_1340_1.jpg
📄 IMG_1343.jpg
📄 IMG_1344_1.jpg
📄 IMG_1347.jpg
📄 IMG_1348_1.jpg
📄 IMG_1349.jpg
📄 IMG_1351.jpg
📄 IMG_1352.jpg
📄 IMG_1354.jpg
📄 IMG_1355.jpg
📄 IMG_1358.jpg
📄 IMG_1360.jpg
📄 IMG_1361_1.jpg
📄 IMG_1366.jpg
📄 IMG_1367.jpg
📄 IMG_1370.jpg
📄 IMG_1373.jpg
📄 IMG_1375.jpg
📄 IMG_1376.jpg
📄 IMG_1377.jpg
📄 IMG_1379.jpg
📄 IMG_1382_1.jpg
📄 IMG_1383.jpg
📄 IMG_1384.jpg
📄 IMG_1385.jpg
📄 IMG_1386.jpg
📄 IMG_1387.jpg
📄 IMG_1389_1.jpg
📄 IMG_1390.jpg
📄 IMG_1391.jpg
📄 IMG_1392.jpg
📄 IMG_1393.jpg
📄 IMG_1395_1.jpg
📄 IMG_1397.jpg
📄 IMG_1399_1.jpg
📄 IMG_1402.jpg
📄 IMG_1403.jpg
📄 IMG_1406.jpg
📄 IMG_1410.jpg
📄 IMG_1411.jpg
📄 IMG_1412.jpg
📄 IMG_1413.jpg
📄 IMG_1416.jpg
📄 IMG_1417.jpg
📄 IMG_1422.jpg
📄 IMG_1423_1.jpg
📄 IMG_1424_2.jpg
📄 IMG_1426_1.jpg
📄 IMG_1428.jpg
📄 IMG_1430.jpg
📄 IMG_1433_1.jpg
📄 IMG_1437.jpg
📄 IMG_1439.jpg
📄 IMG_1440.jpg
📄 IMG_1442_1.jpg
📄 IMG_1444.jpg
📄 IMG_1445.jpg
📄 IMG_1446.jpg
📄 IMG_1447.jpg
📄 IMG_1448.jpg
📄 IMG_1449.jpg
📄 IMG_1450.jpg
📄 IMG_1452.jpg
📄 IMG_1455.jpg
📄 IMG_1456.jpg
📄 IMG_1457.jpg
📄 IMG_1458.jpg
📄 IMG_1459.jpg
📄 IMG_1460_1.jpg
📄 IMG_1463.jpg
📄 IMG_1464.jpg
📄 IMG_1465_1.jpg
📄 IMG_1467.jpg
📄 IMG_1471_1.jpg
📄 IMG_1473_1.jpg
📄 IMG_1475.jpg
📄 IMG_1476.jpg
📄 IMG_1477.jpg
📄 IMG_1480.jpg
📄 IMG_1481.jpg
📄 IMG_1484.jpg
📄 IMG_1486.jpg
📄 IMG_1488.jpg
📄 IMG_1489.jpg
📄 IMG_1491.jpg
📄 IMG_1492.jpg
📄 IMG_1493.jpg
📄 IMG_1497.jpg
📄 IMG_1500.jpg
📄 IMG_1502.jpg
📄 IMG_1504.jpg
📄 IMG_1511.jpg
📄 IMG_1515.jpg
📄 IMG_1517.jpg
📄 IMG_1523.jpg
📄 IMG_1527.jpg
📄 IMG_1530.jpg
📄 IMG_1532.jpg
📄 IMG_1543.jpg
📄 IMG_1550_1.jpg
📄 IMG_1559.jpg
📄 IMG_1563_1.jpg
📄 IMG_1564.jpg
📄 IMG_1567.jpg
📄 IMG_1568.jpg
📄 IMG_1574.jpg
📄 IMG_1576.jpg
📄 IMG_1583.jpg
📄 IMG_1584_1.jpg
📄 IMG_1587.jpg
📄 IMG_1588_1.jpg
📄 IMG_1599_1.jpg
📄 IMG_1602_1.jpg
📄 IMG_1604.jpg
📄 IMG_1607.jpg
📄 IMG_1611.jpg
📄 IMG_1614.jpg
📄 IMG_1615.jpg
📄 IMG_1617.jpg
📄 IMG_1619.jpg
📄 IMG_1620.jpg
📄 IMG_1621.jpg
📄 IMG_1622.jpg
📄 IMG_1625.jpg
📄 IMG_1629.jpg
📄 IMG_1630.jpg
📄 IMG_1631.jpg
📄 IMG_1633.jpg
📄 IMG_1634.jpg
📄 IMG_1640.jpg
📄 IMG_1641.jpg
📄 IMG_1642.jpg
📄 IMG_1642_1.jpg
📄 IMG_1643.jpg
📄 IMG_1644.jpg
📄 IMG_1645.jpg
📄 IMG_1646.jpg
📄 IMG_1648.jpg
📄 IMG_1649.jpg
📄 IMG_1652.jpg
📄 IMG_1654.jpg
📄 IMG_1655.jpg
📄 IMG_1658.jpg
📄 IMG_1659.jpg
📄 IMG_1661.jpg
📄 IMG_1664.jpg
📄 IMG_1666.jpg
📄 IMG_1668.jpg
📄 IMG_1671.jpg
📄 IMG_1673.jpg
📄 IMG_1674.jpg
📄 IMG_1675.jpg
📄 IMG_1676.jpg
📄 IMG_1677.jpg
📄 IMG_1680.jpg
📄 IMG_1683.jpg
📄 IMG_1684.jpg
📄 IMG_1685.jpg
📄 IMG_1687.jpg
📄 IMG_1688.jpg
📄 IMG_1690.jpg
📄 IMG_1691.jpg
📄 IMG_1692.jpg
📄 IMG_1693.jpg
📄 IMG_1699.jpg
📄 IMG_1702.jpg
📄 IMG_1706.jpg
📄 IMG_1707.jpg
📄 IMG_1708.jpg
📄 IMG_1710_1.jpg
📄 IMG_1710_2.jpg
📄 IMG_1712.jpg
📄 IMG_1717.jpg
📄 IMG_1718.jpg
📄 IMG_1719.jpg
📄 IMG_1720.jpg
📄 IMG_1721.jpg
📄 IMG_1724.jpg
📄 IMG_1726.jpg
📄 IMG_1728.jpg
📄 IMG_1729.jpg
📄 IMG_1730.jpg
📄 IMG_1731.jpg
📄 IMG_1732.jpg
📄 IMG_1734.jpg
📄 IMG_1735.jpg
📄 IMG_1736.jpg
📄 IMG_1739.jpg
📄 IMG_1740.jpg
📄 IMG_1741.jpg
📄 IMG_1744.jpg
📄 IMG_1745.jpg
📄 IMG_1747.jpg
📄 IMG_1750.jpg
📄 IMG_1751.jpg
📄 IMG_1753.jpg
📄 IMG_1757.jpg
📄 IMG_1759.jpg
📄 IMG_1760.jpg
📄 IMG_1763.jpg
📄 IMG_1764.jpg
📄 IMG_1767.jpg
📄 IMG_1768.jpg
📄 IMG_1769.jpg
📄 IMG_1770.jpg
📄 IMG_1772.jpg
📄 IMG_1773.jpg
📄 IMG_1777.jpg
📄 IMG_1779.jpg
📄 IMG_1782.jpg
📄 IMG_1784.jpg
📄 IMG_1786.jpg
📄 IMG_1787.jpg
📄 IMG_1789.jpg
📄 IMG_1793.jpg
📄 IMG_1794.jpg
📄 IMG_1796.jpg
📄 IMG_1800.jpg
📄 IMG_1803.jpg
📄 IMG_1804.jpg
📄 IMG_1805.jpg
📄 IMG_1810.jpg
📄 IMG_1823.jpg
📄 IMG_1834.jpg
📄 IMG_1840.jpg
📄 IMG_1844.jpg
📄 IMG_1849.jpg
📄 IMG_1850.jpg
📄 IMG_1853.jpg
📄 IMG_1865.jpg
📄 IMG_1870.jpg
📄 IMG_1883.jpg
📄 IMG_1889.jpg
📄 IMG_1891.jpg
📄 IMG_1894.jpg
📄 IMG_1897.jpg
📄 IMG_1899.jpg
📄 IMG_1903.jpg
📄 IMG_1905.jpg
📄 IMG_1911.jpg
📄 IMG_1916.jpg
📄 IMG_1918.jpg
📄 IMG_1919.jpg
📄 IMG_1923.jpg
📄 IMG_1924.jpg
📄 IMG_1933.jpg
📄 IMG_1936.jpg
📄 IMG_1940_1.jpg
📄 IMG_1940_2.jpg
📄 IMG_1942.jpg
📄 IMG_1943.jpg
📄 IMG_1944.jpg
📄 IMG_1951.jpg
📄 IMG_1952.jpg
📄 IMG_1953.jpg
📄 IMG_1954.jpg
📄 IMG_1961.jpg
📄 IMG_1962_1.jpg
📄 IMG_1962_2.jpg
📄 IMG_1964.jpg
📄 IMG_1967.jpg
📄 IMG_1971.jpg
📄 IMG_1972.jpg
📄 IMG_1974.jpg
📄 IMG_1975.jpg
📄 IMG_1977.jpg
📄 IMG_1978.jpg
📄 IMG_1980.jpg
📄 IMG_1989.jpg
📄 IMG_1990.jpg
📄 IMG_1995.jpg
📄 IMG_1999.jpg
📄 IMG_2003.jpg
📄 IMG_2004_1.jpg
📄 IMG_2004_2.jpg
📄 IMG_2006.jpg
📄 IMG_2008.jpg
📄 IMG_2009.jpg
📄 IMG_2011.jpg
📄 IMG_2014.jpg
📄 IMG_2015.jpg
📄 IMG_2016.jpg
📄 IMG_2019_1.jpg
📄 IMG_2020.jpg
📄 IMG_2023.jpg
📄 IMG_2024.jpg
📄 IMG_2027.jpg
📄 IMG_2028.jpg
📄 IMG_2035_1.jpg
📄 IMG_2037_1.jpg
📄 IMG_2037_2.jpg
📄 IMG_2040.jpg
📄 IMG_2041.jpg
📄 IMG_2042.jpg
📄 IMG_2044.jpg
📄 IMG_2047.jpg
📄 IMG_2047_1.jpg
📄 IMG_2048_1.jpg
📄 IMG_2050.jpg
📄 IMG_2055.jpg
📄 IMG_2056.jpg
📄 IMG_2057.jpg
📄 IMG_2058_1.jpg
📄 IMG_2059.jpg
📄 IMG_2060.jpg
📄 IMG_2061.jpg
📄 IMG_2067.jpg
📄 IMG_2069.jpg
📄 IMG_2071.jpg
📄 IMG_2073.jpg
📄 IMG_2074.jpg
📄 IMG_2075.jpg
📄 IMG_2076.jpg
📄 IMG_2077.jpg
📄 IMG_2079.jpg
📄 IMG_2081.jpg
📄 IMG_2082.jpg
📄 IMG_2084.jpg
📄 IMG_2086.jpg
📄 IMG_2087.jpg
📄 IMG_2092.jpg
📄 IMG_2094.jpg
📄 IMG_2099.jpg
📄 IMG_2101.jpg
📄 IMG_2102.jpg
📄 IMG_2104.jpg
📄 IMG_2105.jpg
📄 IMG_2107.jpg
📄 IMG_2110.jpg
📄 IMG_2112.jpg
📄 IMG_2115.jpg
📄 IMG_2116.jpg
📄 IMG_2117.jpg
📄 IMG_2119.jpg
📄 IMG_2121.jpg
📄 IMG_2122.jpg
📄 IMG_2123.jpg
📄 IMG_2124.jpg
📄 IMG_2125.jpg
📄 IMG_2126.jpg
📄 IMG_2128.jpg
📄 IMG_2130.jpg
📄 IMG_2131.jpg
📄 IMG_2133.jpg
📄 IMG_2136.jpg
📄 IMG_2137.jpg
📄 IMG_2139.jpg
📄 IMG_2145.jpg
📄 IMG_2149.jpg
📄 IMG_2150.jpg
📄 IMG_2152.jpg
📄 IMG_2153.jpg
📄 IMG_2155.jpg
📄 IMG_2156.jpg
📄 IMG_2158.jpg
📄 IMG_2166.jpg
📄 IMG_2169.jpg
📄 IMG_2171.jpg
📄 IMG_2173.jpg
📄 IMG_2181.jpg
📄 IMG_2182.jpg
📄 IMG_2185.jpg
📄 IMG_2192.jpg
📄 IMG_2198.jpg
📄 IMG_2201.jpg
📄 IMG_2203.jpg
📄 IMG_2221.jpg
📄 IMG_2226.jpg
📄 IMG_2233.jpg
📄 IMG_2235.jpg
📄 IMG_2240.jpg
📄 IMG_2241.jpg
📄 IMG_2243.jpg
📄 IMG_2244.jpg
📄 IMG_2261.jpg
📄 IMG_2263.jpg
📄 IMG_2265.jpg
📄 IMG_2268.jpg
📄 IMG_2271.jpg
📄 IMG_2272.jpg
📄 IMG_2273.jpg
📄 IMG_2275.jpg
📄 IMG_2276.jpg
📄 IMG_2277.jpg
📄 IMG_2279.jpg
📄 IMG_2282.jpg
📄 IMG_2284.jpg
📄 IMG_2287.jpg
📄 IMG_2288.jpg
📄 IMG_2290.jpg
📄 IMG_2293.jpg
📄 IMG_2297.jpg
📄 IMG_2300.jpg
📄 IMG_2301.jpg
📄 IMG_2302.jpg
📄 IMG_2306.jpg
📄 IMG_2308.jpg
📄 IMG_2309.jpg
📄 IMG_2313.jpg
📄 IMG_2314.jpg
📄 IMG_2316.jpg
📄 IMG_2317.jpg
📄 IMG_2318.jpg
📄 IMG_2320.jpg
📄 IMG_2325.jpg
📄 IMG_2335.jpg
📄 IMG_2343.jpg
📄 IMG_2350.jpg
📄 IMG_2355.jpg
📄 IMG_2365.jpg
📄 IMG_2367.jpg
📄 IMG_2369.jpg
📄 IMG_2371.jpg
📄 IMG_2399.jpg
📄 IMG_2401.jpg
📄 IMG_2404.jpg
📄 IMG_2406.jpg
📄 IMG_2407.jpg
📄 IMG_2409.jpg
📄 IMG_2411.jpg
📄 IMG_2414.jpg
📄 IMG_2415.jpg
📄 IMG_2416.jpg
📄 IMG_2417.jpg
📄 IMG_2419.jpg
📄 IMG_2420.jpg
📄 IMG_2422.jpg
📄 IMG_2423.jpg
📄 IMG_2426.jpg
📄 IMG_2427.jpg
📄 IMG_2431.jpg
📄 IMG_2435.jpg
📄 IMG_2437.jpg
📄 IMG_2439.jpg
📄 IMG_2441.jpg
📄 IMG_2444.jpg
📄 IMG_2446.jpg
📄 IMG_2447.jpg
📄 IMG_2448_1.jpg
📄 IMG_2451_1.jpg
📄 IMG_2452_1.jpg
📄 IMG_2456_1.jpg
📄 IMG_2458_1.jpg
📄 IMG_2460.jpg
📄 IMG_2461.jpg
📄 IMG_2463_1.jpg
📄 IMG_2466.jpg
📄 IMG_2467_1.jpg
📄 IMG_2469.jpg
📄 IMG_2472.jpg
📄 IMG_2474_1.jpg
📄 IMG_2477.jpg
📄 IMG_2480_1.jpg
📄 IMG_2485.jpg
📄 IMG_2486_1.jpg
📄 IMG_2487.jpg
📄 IMG_2487_1.jpg
📄 IMG_2489_1.jpg
📄 IMG_2491_1.jpg
📄 IMG_2492_1.jpg
📄 IMG_2493_1.jpg
📄 IMG_2495_1.jpg
📄 IMG_2497.jpg
📄 IMG_2498.jpg
📄 IMG_2499.jpg
📄 IMG_2504_1.jpg
📄 IMG_2505_1.jpg
📄 IMG_2507_1.jpg
📄 IMG_2509_1.jpg
📄 IMG_2511_1.jpg
📄 IMG_2512.jpg
📄 IMG_2515.jpg
📄 IMG_2516.jpg
📄 IMG_2518.jpg
📄 IMG_2520_1.jpg
📄 IMG_2523.jpg
📄 IMG_2525.jpg
📄 IMG_2527.jpg
📄 IMG_2529.jpg
📄 IMG_2531.jpg
📄 IMG_2532.jpg
📄 IMG_2533.jpg
📄 IMG_2536_1.jpg
📄 IMG_2537.jpg
📄 IMG_2539.jpg
📄 IMG_2541_1.jpg
📄 IMG_2542.jpg
📄 IMG_2543_1.jpg
📄 IMG_2544_1.jpg
📄 IMG_2545.jpg
📄 IMG_2546_1.jpg
📄 IMG_2549_1.jpg
📄 IMG_2550.jpg
📄 IMG_2550_1.jpg
📄 IMG_2551_1.jpg
📄 IMG_2552_1.jpg
📄 IMG_2553_1.jpg
📄 IMG_2554_1.jpg
📄 IMG_2555_1.jpg
📄 IMG_2556_1.jpg
📄 IMG_2556_2.jpg
📄 IMG_2557_1.jpg
📄 IMG_2559.jpg
📄 IMG_2562_1.jpg
📄 IMG_2564_1.jpg
📄 IMG_2565_1.jpg
📄 IMG_2566_1.jpg
📄 IMG_2568.jpg
📄 IMG_2569_1.jpg
📄 IMG_2573_1.jpg
📄 IMG_2575_1.jpg
📄 IMG_2578_1.jpg
📄 IMG_2581.jpg
📄 IMG_2594_1.jpg
📄 IMG_2594_2.jpg
📄 IMG_2596.jpg
📄 IMG_2598_1.jpg
📄 IMG_2599_1.jpg
📄 IMG_2600_1.jpg
📄 IMG_2602.jpg
📄 IMG_2604.jpg
📄 IMG_2607_1.jpg
📄 IMG_2610.jpg
📄 IMG_2611_1.jpg
📄 IMG_2613_1.jpg
📄 IMG_2616_1.jpg
📄 IMG_2618.jpg
📄 IMG_2620_1.jpg
📄 IMG_2620_2.jpg
📄 IMG_2622_1.jpg
📄 IMG_2624_1.jpg
📄 IMG_2627_1.jpg
📄 IMG_2629_1.jpg
📄 IMG_2631.jpg
📄 IMG_2633_1.jpg
📄 IMG_2647.jpg
📄 IMG_2656.jpg
📄 IMG_2659.jpg
📄 IMG_2662.jpg
📄 IMG_2664.jpg
📄 IMG_2668_1.jpg
📄 IMG_2671_1.jpg
📄 IMG_2674_1.jpg
📄 IMG_2681.jpg
📄 IMG_2686.jpg
📄 IMG_2689_1.jpg
📄 IMG_2691_1.jpg
📄 IMG_2692_1.jpg
📄 IMG_2695_1.jpg
📄 IMG_2697_1.jpg
📄 IMG_2699.jpg
📄 IMG_2707_1.jpg
📄 IMG_2709_1.jpg
📄 IMG_2710_1.jpg
📄 IMG_2711_1.jpg
📄 IMG_2713.jpg
📄 IMG_2717.jpg
📄 IMG_2718.jpg
📄 IMG_2720_1.jpg
📄 IMG_2722.jpg
📄 IMG_2724_1.jpg
📄 IMG_2726_1.jpg
📄 IMG_2728.jpg
📄 IMG_2730.jpg
📄 IMG_2732.jpg
📄 IMG_2734_1.jpg
📄 IMG_2736.jpg
📄 IMG_2738_1.jpg
📄 IMG_2741.jpg
📄 IMG_2742_1.jpg
📄 IMG_2745_1.jpg
📄 IMG_2747_1.jpg
📄 IMG_2748_1.jpg
📄 IMG_2752_1.jpg
📄 IMG_2754_1.jpg
📄 IMG_2755_1.jpg
📄 IMG_2755_2.jpg
📄 IMG_2756.jpg
📄 IMG_2758.jpg
📄 IMG_2760.jpg
📄 IMG_2764.jpg
📄 IMG_2766.jpg
📄 IMG_2769.jpg
📄 IMG_2771.jpg
📄 IMG_2773.jpg
📄 IMG_2774.jpg
📄 IMG_2775.jpg
📄 IMG_2777.jpg
📄 IMG_2780.jpg
📄 IMG_2781.jpg
📄 IMG_2784.jpg
📄 IMG_2786.jpg
📄 IMG_2787.jpg
📄 IMG_2789.jpg
📄 IMG_2791.jpg
📄 IMG_2793.jpg
📄 IMG_2795.jpg
📄 IMG_2797.jpg
📄 IMG_2804.jpg
📄 IMG_2806.jpg
📄 IMG_2807.jpg
📄 IMG_2809.jpg
📄 IMG_2810.jpg
📄 IMG_2812.jpg
📄 IMG_2814.jpg
📄 IMG_2816.jpg
📄 IMG_2818.jpg
📄 IMG_2821.jpg
📄 IMG_2822.jpg
📄 IMG_2825.jpg
📄 IMG_2827.jpg
📄 IMG_2828.jpg
📄 IMG_2829.jpg
📄 IMG_2832.jpg
📄 IMG_2834.jpg
📄 IMG_2835.jpg
📄 IMG_2837.jpg
📄 IMG_2838.jpg
📄 IMG_2840.jpg
📄 IMG_2843.jpg
📄 IMG_2845.jpg
📄 IMG_2848.jpg
📄 IMG_2850.jpg
📄 IMG_2852.jpg
📄 IMG_2854.jpg
📄 IMG_2858.jpg
📄 IMG_2861.jpg
📄 IMG_2862.jpg
📄 IMG_2865.jpg
📄 IMG_2868.jpg
📄 IMG_2871.jpg
📄 IMG_2873.jpg
📄 IMG_2874.jpg
📄 IMG_2876.jpg
📄 IMG_2877.jpg
📄 IMG_2880.jpg
📄 IMG_2881.jpg
📄 IMG_2884.jpg
📄 IMG_2888.jpg
📄 IMG_2891.jpg
📄 IMG_2892.jpg
📄 IMG_2894.jpg
📄 IMG_2897.jpg
📄 IMG_2900.jpg
📄 IMG_2902.jpg
📄 IMG_2903.jpg
📄 IMG_2905.jpg
📄 IMG_2908.jpg
📄 IMG_2909.jpg
📄 IMG_2911.jpg
📄 IMG_2913.jpg
📄 IMG_2915.jpg
📄 IMG_2917.jpg
📄 IMG_2919.jpg
📄 IMG_2921.jpg
📄 IMG_2923.jpg
📄 IMG_2926.jpg
📄 IMG_2928.jpg
📄 IMG_2930.jpg
📄 IMG_2931.jpg
📄 IMG_2934.jpg
📄 IMG_2935.jpg
📄 IMG_2937.jpg
📄 IMG_2938.jpg
📄 IMG_2939.jpg
📄 IMG_2940.jpg
📄 IMG_2941.jpg
📄 IMG_2946.jpg
📄 IMG_2948.jpg
📄 IMG_2950.jpg
📄 IMG_2950_1.jpg
📄 IMG_2952.jpg
📄 IMG_2953.jpg
📄 IMG_2955.jpg
📄 IMG_2957.jpg
📄 IMG_2958.jpg
📄 IMG_2960.jpg
📄 IMG_2961.jpg
📄 IMG_2962.jpg
📄 IMG_2964.jpg
📄 IMG_2965_1.jpg
📄 IMG_2966.jpg
📄 IMG_2970.jpg
📄 IMG_2971.jpg
📄 IMG_2972.jpg
📄 IMG_2973.jpg
📄 IMG_2975.jpg
📄 IMG_2976.jpg
📄 IMG_2982.jpg
📄 IMG_2986_1.jpg
📄 IMG_2986_2.jpg
📄 IMG_2988.jpg
📄 IMG_2992.jpg
📄 IMG_2995_1.jpg
📄 IMG_2995_2.jpg
📄 IMG_3001.jpg
📄 IMG_3003.jpg
📄 IMG_3008.jpg
📄 IMG_3010.jpg
📄 IMG_3016.jpg
📄 IMG_3018.jpg
📄 IMG_3019.jpg
📄 IMG_3021.jpg
📄 IMG_3022.jpg
📄 IMG_3023.jpg
📄 IMG_3024.jpg
📄 IMG_3030.jpg
📄 IMG_3032.jpg
📄 IMG_3035.jpg
📄 IMG_3038.jpg
📄 IMG_3039.jpg
📄 IMG_3043.jpg
📄 IMG_3045.jpg
📄 IMG_3048.jpg
📄 IMG_3050.jpg
📄 IMG_3052.jpg
📄 IMG_3056.jpg
📄 IMG_3062.jpg
📄 IMG_3063.jpg
📄 IMG_3065.jpg
📄 IMG_3070.jpg
📄 IMG_3073.jpg
📄 IMG_3077.jpg
📄 IMG_3079.jpg
📄 IMG_3082.jpg

In [4]:
from pathlib import Path

root = Path("/kaggle/input/datasets/abhig888/dermacon-in/METADATA")

print("METADATA:", root)
print("\nInside METADATA:\n")

for item in sorted(root.iterdir()):
    if item.is_dir():
        print("📁", item.name)
    else:
        print("📄", item.name)

METADATA: /kaggle/input/datasets/abhig888/dermacon-in/METADATA

Inside METADATA:

📄 Skin_Metadata-1.csv
📄 test_split-1.csv
📄 train_split-1.csv

In [5]:
import pandas as pd
from pathlib import Path

csv_path = Path(
    "/kaggle/input/datasets/abhig888/dermacon-in/METADATA/Skin_Metadata-1.csv"
)

df = pd.read_csv(csv_path)

print("Shape:", df.shape)

print("\nColumns:")
for col in df.columns:
    print(" -", col)

print("\nFirst 5 rows:")
display(df.head())

Shape: (5450, 14)

Columns:
 - Age
 - Body_part
 - Descriptors
 - Confidence
 - Disease_label
 - Fitzpatrick
 - Gradability
 - Image_name
 - Main_class
 - Monk_skin_tone
 - Quality
 - Sex
 - Sub_class
 - Subject_ID

First 5 rows:

,Age,Body_part,Descriptors,Confidence,Disease_label,Fitzpatrick,Gradability,Image_name,Main_class,Monk_skin_tone,Quality,Sex,Sub_class,Subject_ID
0,10 - 20,"Groin (Inguinal Region),Lower Extremities Thig...","Erythema, Pigmented, Plaque",5,Steroid Modified Tinea,FST 3,Yes,IMG_0002.jpg,Infectious Disorders,MST 5,"Yes, the quality is sufficient for me or anoth...",Male,Infectious skin conditions -Fungal,SUB00001
1,10 - 20,"Groin (Inguinal Region),Lower Extremities Thig...","Erythema, Pigmented, Plaque",5,Steroid Modified Tinea,FST 3,Yes,IMG_0005.jpg,Infectious Disorders,MST 5,"Yes, the quality is sufficient for me or anoth...",Male,Infectious skin conditions -Fungal,SUB00001
2,40 - 60,Head Cheeks,Papule,5,Acne,FST 4,Yes,IMG_0009.jpg,Skin Appendages Disorders,MST 6,"Yes, the quality is sufficient for me or anoth...",Female,Sebacious Glands and Acneiform Disorders,SUB00002
3,40 - 60,Head Cheeks,Papule,5,Acne,FST 4,Yes,IMG_0010.jpg,Skin Appendages Disorders,MST 6,"Yes, the quality is sufficient for me or anoth...",Female,Sebacious Glands and Acneiform Disorders,SUB00002
4,40 - 60,"Head Cheeks,Head Nose,Head Lips",Papule,5,Acne,FST 4,Yes,IMG_0011.jpg,Skin Appendages Disorders,MST 6,"Yes, the quality is sufficient for me or anoth...",Female,Sebacious Glands and Acneiform Disorders,SUB00002

In [6]:
# Check disease labels available in DermaCon

cancer_keywords = [
    "melanoma",
    "basal cell",
    "squamous cell",
    "merkel"
]

disease_counts = (
    df["Disease_label"]
    .astype(str)
    .str.strip()
    .value_counts()
)

print("Disease labels matching our target cancer classes:\n")

found = False

for disease, count in disease_counts.items():
    disease_lower = disease.lower()

    if any(keyword in disease_lower for keyword in cancer_keywords):
        print(f"{disease}  -->  {count} images")
        found = True

if not found:
    print("❌ No target cancer labels found.")

Disease labels matching our target cancer classes:

Basal Cell Carcinoma  -->  10 images
Squamous Cell Carcinoma  -->  5 images
Melanoma  -->  2 images

In [7]:
print("Total unique disease labels:", df["Disease_label"].nunique())

print("\nAll disease labels and counts:\n")

display(
    df["Disease_label"]
    .astype(str)
    .str.strip()
    .value_counts()
    .to_frame("Image_Count")
)

Total unique disease labels: 245

All disease labels and counts:

                                                    Image_Count
Disease_label
Vitiligo                                                    601
Tinea Cruris                                                545
Tinea Corporis                                              323
Scabies                                                     183
Acne                                                        181
...                                                         ...
Perioral dermatitis                                           1
Kerion                                                        1
Myxoid Cyst                                                   1
Trophic Ulcer                                                 1
SLE - Systemic lupus erythematosus-related synd...            1

[245 rows x 1 columns]

In [8]:
# Check cancer-related records using all relevant label columns

keywords = [
    "melanoma",
    "basal cell",
    "squamous cell",
    "merkel"
]

mask = (
    df["Disease_label"].astype(str).str.lower().str.contains("|".join(keywords), regex=True)
    | df["Main_class"].astype(str).str.lower().str.contains("|".join(keywords), regex=True)
    | df["Sub_class"].astype(str).str.lower().str.contains("|".join(keywords), regex=True)
)

cancer_records = df.loc[
    mask,
    [
        "Image_name",
        "Disease_label",
        "Main_class",
        "Sub_class",
        "Age",
        "Body_part",
        "Fitzpatrick",
        "Monk_skin_tone",
        "Sex",
        "Subject_ID"
    ]
]

print("Cancer-related records found:", len(cancer_records))

display(cancer_records)

Cancer-related records found: 17

,Image_name,Disease_label,Main_class,Sub_class,Age,Body_part,Fitzpatrick,Monk_skin_tone,Sex,Subject_ID
76,IMG_0166.jpg,Squamous Cell Carcinoma,Neoplasms and tumors,Neoplasms and tumors,40 - 60,Trunk Abdomen,FST 3,MST 5,Female,SUB00041
802,IMG_1834.jpg,Squamous Cell Carcinoma,Neoplasms and tumors,Neoplasms and tumors,60 - 80,Upper Extremities Shoulders,FST 5,MST 7,Male,SUB00431
873,IMG_20190712_105158.jpg,Squamous Cell Carcinoma,Neoplasms and tumors,Neoplasms and tumors,80 - 100,Head Nose,FST 3,MST 5,Female,SUB01947
877,IMG_20190816_122607_1.jpg,Squamous Cell Carcinoma,Neoplasms and tumors,Neoplasms and tumors,80 - 100,Head Nose,FST 4,MST 6,Female,SUB01947
1039,IMG_20230105_203256.jpg,Basal Cell Carcinoma,Neoplasms and tumors,Neoplasms and tumors,40 - 60,Head Nose,FST 5,MST 7,Male,SUB02498
1040,IMG_20230105_203258_1.jpg,Basal Cell Carcinoma,Neoplasms and tumors,Neoplasms and tumors,40 - 60,Head Nose,FST 5,MST 7,Male,SUB02498
1491,IMG_20230720_122930_BURST3_1.jpg,Basal Cell Carcinoma,Neoplasms and tumors,Neoplasms and tumors,60 - 80,"Head Cheeks,Head Forehead, Head Nose",FST 4,MST 6,Female,SUB02239
1626,IMG_20231117_140137_1.jpg,Squamous Cell Carcinoma,Neoplasms and tumors,Neoplasms and tumors,80 - 100,Head Temples,FST 5,MST 7,Female,SUB02874
1849,IMG_20240611_132130_1.jpg,Basal Cell Carcinoma,Neoplasms and tumors,Neoplasms and tumors,60 - 80,Head Cheeks,FST 5,MST 7,Male,SUB00489
2176,IMG_2807.jpg,Melanoma,Neoplasms and tumors,Neoplasms and tumors,20 - 40,"Back,LowerBack (Lumbus)",FST 3,MST 4,Female,SUB00622
2177,IMG_2809.jpg,Melanoma,Neoplasms and tumors,Neoplasms and tumors,20 - 40,Lower Extremities Thighs (Femoral Region),FST 3,MST 5,Female,SUB00622
2473,IMG_3447.jpg,Basal Cell Carcinoma,Neoplasms and tumors,Neoplasms and tumors,60 - 80,Upper Extremities Shoulders,FST 4,MST 7,Male,SUB00792
4916,IMG_9544_2.jpg,Basal Cell Carcinoma,Neoplasms and tumors,Neoplasms and tumors,60 - 80,"Head Cheeks,Head Forehead",FST 4,MST 6,Female,SUB02170
5019,IMG_9920_1.jpg,Basal Cell Carcinoma,Neoplasms and tumors,Neoplasms and tumors,60 - 80,"Head Cheeks,Head Eye,Head Forehead",FST 3,MST 6,Female,SUB02170
5020,IMG_9922.jpg,Basal Cell Carcinoma,Neoplasms and tumors,Neoplasms and tumors,60 - 80,"Head Cheeks,Head Eye,Head Forehead",FST 3,MST 6,Female,SUB02170
5032,IMG_9943_1.jpg,Basal Cell Carcinoma,Neoplasms and tumors,Neoplasms and tumors,60 - 80,"Head Cheeks,Head Forehead,Head Nose",FST 4,MST 7,Female,SUB02239
5181,IMG20240705125445_1.jpg,Basal Cell Carcinoma,Neoplasms and tumors,Neoplasms and tumors,60 - 80,Head Cheeks,FST 3,MST 5,Female,SUB02391

In [9]:
from pathlib import Path

image_root = Path(
    "/kaggle/input/datasets/abhig888/dermacon-in/DATASET"
)

# Get all image filenames inside DATASET
image_files = {}

for p in image_root.rglob("*"):
    if p.is_file() and p.suffix.lower() in {".jpg", ".jpeg", ".png", ".bmp", ".webp"}:
        image_files[p.name.lower()] = str(p)

# Check metadata cancer images against actual files
check = cancer_records.copy()

check["file_found"] = check["Image_name"].astype(str).str.lower().map(
    lambda x: x in image_files
)

print("Total cancer metadata records:", len(check))
print("Images found:", check["file_found"].sum())
print("Images NOT found:", (~check["file_found"]).sum())

print("\nMissing images:")
display(check.loc[~check["file_found"], ["Image_name", "Disease_label"]])

Total cancer metadata records: 17
Images found: 17
Images NOT found: 0

Missing images:

Empty DataFrame
Columns: [Image_name, Disease_label]
Index: []

In [10]:
from pathlib import Path
import pandas as pd

metadata_root = Path(
    "/kaggle/input/datasets/abhig888/dermacon-in/METADATA"
)

for filename in ["train_split-1.csv", "test_split-1.csv"]:

    path = metadata_root / filename
    temp = pd.read_csv(path)

    print("\n" + "=" * 70)
    print(filename)
    print("Shape:", temp.shape)

    print("\nColumns:")
    for col in temp.columns:
        print(" -", col)

    print("\nFirst 5 rows:")
    display(temp.head())

======================================================================
train_split-1.csv
Shape: (4399, 108)

Columns:
 - Age
 - Body_part_Armpits (Axillary Region)
 - Body_part_Back
 - Body_part_Back of the Knees (Popliteal Region)
 - Body_part_Breasts (Mammary Region)
 - Body_part_Calves (Sural Region)
 - Body_part_Genital Area (Pubic Region)
 - Body_part_Groin (Inguinal Region)
 - Body_part_Head Cheeks
 - Body_part_Head Chin
 - Body_part_Head Ears
 - Body_part_Head Eye
 - Body_part_Head Forehead
 - Body_part_Head Lips
 - Body_part_Head Nose
 - Body_part_Head Scalp
 - Body_part_Head Temples
 - Body_part_Lower Extremities Ankles (Tarsal Region)
 - Body_part_Lower Extremities Feet (Pedal Region)
 - Body_part_Lower Extremities Feet (Pedal Region) Toes (Digits)
 - Body_part_Lower Extremities Hips (Coxal Region)
 - Body_part_Lower Extremities Knees (Patellar Region)
 - Body_part_Lower Extremities Lower Legs
 - Body_part_Lower Extremities Lower Legs (Crural Region)
 - Body_part_Lower Extremities Soles (Plantar Region)
 - Body_part_Lower Extremities Thighs (Femoral Region)
 - Body_part_Lower Extremities Toes (Digits)
 - Body_part_LowerBack (Lumbus)
 - Body_part_Mucous Membranes Oral Cavity
 - Body_part_Nails Fingernails
 - Body_part_Nails Toenails
 - Body_part_Navel (Umbilicus)
 - Body_part_Neck
 - Body_part_Palms
 - Body_part_Perianal Area
 - Body_part_Tongue
 - Body_part_Trunk Abdomen
 - Body_part_Trunk Abdomen Navel (Umbilicus)
 - Body_part_Trunk Abdomen anterior
 - Body_part_Trunk Abdomen posterior
 - Body_part_Trunk Back (Dorsum)
 - Body_part_Trunk Buttocks (Gluteal Region)
 - Body_part_Trunk Chest (Thorax)
 - Body_part_Upper Extremities Elbows
 - Body_part_Upper Extremities Forearms (Antebrachium)
 - Body_part_Upper Extremities Hands (Manus)
 - Body_part_Upper Extremities Hands (Manus) Fingers (Digits)
 - Body_part_Upper Extremities Shoulders
 - Body_part_Upper Extremities Upper Arms (Brachium)
 - Body_part_Upper Extremities Wrists (Carpus)
 - Descriptor_Abscess
 - Descriptor_Acuminate
 - Descriptor_Atrophy
 - Descriptor_Brown (Hyperpigmentation)
 - Descriptor_Bulla
 - Descriptor_Burrow
 - Descriptor_Comedo
 - Descriptor_Crust
 - Descriptor_Cyst
 - Descriptor_Dilated Vein
 - Descriptor_Discolored Nail
 - Descriptor_Edema
 - Descriptor_Erosion
 - Descriptor_Erythema
 - Descriptor_Excoriation
 - Descriptor_Exophytic/Fungating
 - Descriptor_Exudate
 - Descriptor_Fissure
 - Descriptor_Flat-topped
 - Descriptor_Gray
 - Descriptor_Hair Patch
 - Descriptor_Hyperkeratotic plaques
 - Descriptor_Induration
 - Descriptor_Lichenification
 - Descriptor_Macule
 - Descriptor_Nodule
 - Descriptor_Papule
 - Descriptor_Patch
 - Descriptor_Pedunculated
 - Descriptor_Pigmented
 - Descriptor_Pitted Nail
 - Descriptor_Plaque
 - Descriptor_Poikiloderma
 - Descriptor_Purpura/Petechiae
 - Descriptor_Pustule
 - Descriptor_Salmon
 - Descriptor_Scale
 - Descriptor_Scar
 - Descriptor_Striae
 - Descriptor_Telangiectasia
 - Descriptor_Ulcer
 - Descriptor_Vesicle
 - Descriptor_Warty
 - Descriptor_Wheal
 - Descriptor_White (Hypopigmentation)
 - Descriptor_Xerosis
 - Descriptor_Yellow
 - Confidence
 - Disease_label
 - Fitzpatrick
 - Gradability
 - Image_name
 - Main_class
 - Monk_skin_tone
 - Quality
 - Sex
 - Sub_class
 - Subject_ID

First 5 rows:

,Age,Body_part_Armpits (Axillary Region),Body_part_Back,Body_part_Back of the Knees (Popliteal Region),Body_part_Breasts (Mammary Region),Body_part_Calves (Sural Region),Body_part_Genital Area (Pubic Region),Body_part_Groin (Inguinal Region),Body_part_Head Cheeks,Body_part_Head Chin,...,Disease_label,Fitzpatrick,Gradability,Image_name,Main_class,Monk_skin_tone,Quality,Sex,Sub_class,Subject_ID
0,10 - 20,0,0,0,0,0,0,1,0,0,...,Steroid Modified Tinea,FST 3,Yes,IMG_0002.jpg,Infectious Disorders,MST 5,"Yes, the quality is sufficient for me or anoth...",Male,Infectious skin conditions -Fungal,SUB00001
1,10 - 20,0,0,0,0,0,0,1,0,0,...,Steroid Modified Tinea,FST 3,Yes,IMG_0005.jpg,Infectious Disorders,MST 5,"Yes, the quality is sufficient for me or anoth...",Male,Infectious skin conditions -Fungal,SUB00001
2,40 - 60,0,0,0,0,0,0,0,1,0,...,Acne,FST 4,Yes,IMG_0009.jpg,Skin Appendages Disorders,MST 6,"Yes, the quality is sufficient for me or anoth...",Female,Sebacious Glands and Acneiform Disorders,SUB00002
3,40 - 60,0,0,0,0,0,0,0,1,0,...,Acne,FST 4,Yes,IMG_0010.jpg,Skin Appendages Disorders,MST 6,"Yes, the quality is sufficient for me or anoth...",Female,Sebacious Glands and Acneiform Disorders,SUB00002
4,40 - 60,0,0,0,0,0,0,0,1,0,...,Acne,FST 4,Yes,IMG_0011.jpg,Skin Appendages Disorders,MST 6,"Yes, the quality is sufficient for me or anoth...",Female,Sebacious Glands and Acneiform Disorders,SUB00002

======================================================================
test_split-1.csv
Shape: (1051, 108)

Columns:
 - Age
 - Body_part_Armpits (Axillary Region)
 - Body_part_Back
 - Body_part_Back of the Knees (Popliteal Region)
 - Body_part_Breasts (Mammary Region)
 - Body_part_Calves (Sural Region)
 - Body_part_Genital Area (Pubic Region)
 - Body_part_Groin (Inguinal Region)
 - Body_part_Head Cheeks
 - Body_part_Head Chin
 - Body_part_Head Ears
 - Body_part_Head Eye
 - Body_part_Head Forehead
 - Body_part_Head Lips
 - Body_part_Head Nose
 - Body_part_Head Scalp
 - Body_part_Head Temples
 - Body_part_Lower Extremities Ankles (Tarsal Region)
 - Body_part_Lower Extremities Feet (Pedal Region)
 - Body_part_Lower Extremities Feet (Pedal Region) Toes (Digits)
 - Body_part_Lower Extremities Hips (Coxal Region)
 - Body_part_Lower Extremities Knees (Patellar Region)
 - Body_part_Lower Extremities Lower Legs
 - Body_part_Lower Extremities Lower Legs (Crural Region)
 - Body_part_Lower Extremities Soles (Plantar Region)
 - Body_part_Lower Extremities Thighs (Femoral Region)
 - Body_part_Lower Extremities Toes (Digits)
 - Body_part_LowerBack (Lumbus)
 - Body_part_Mucous Membranes Oral Cavity
 - Body_part_Nails Fingernails
 - Body_part_Nails Toenails
 - Body_part_Navel (Umbilicus)
 - Body_part_Neck
 - Body_part_Palms
 - Body_part_Perianal Area
 - Body_part_Tongue
 - Body_part_Trunk Abdomen
 - Body_part_Trunk Abdomen Navel (Umbilicus)
 - Body_part_Trunk Abdomen anterior
 - Body_part_Trunk Abdomen posterior
 - Body_part_Trunk Back (Dorsum)
 - Body_part_Trunk Buttocks (Gluteal Region)
 - Body_part_Trunk Chest (Thorax)
 - Body_part_Upper Extremities Elbows
 - Body_part_Upper Extremities Forearms (Antebrachium)
 - Body_part_Upper Extremities Hands (Manus)
 - Body_part_Upper Extremities Hands (Manus) Fingers (Digits)
 - Body_part_Upper Extremities Shoulders
 - Body_part_Upper Extremities Upper Arms (Brachium)
 - Body_part_Upper Extremities Wrists (Carpus)
 - Descriptor_Abscess
 - Descriptor_Acuminate
 - Descriptor_Atrophy
 - Descriptor_Brown (Hyperpigmentation)
 - Descriptor_Bulla
 - Descriptor_Burrow
 - Descriptor_Comedo
 - Descriptor_Crust
 - Descriptor_Cyst
 - Descriptor_Dilated Vein
 - Descriptor_Discolored Nail
 - Descriptor_Edema
 - Descriptor_Erosion
 - Descriptor_Erythema
 - Descriptor_Excoriation
 - Descriptor_Exophytic/Fungating
 - Descriptor_Exudate
 - Descriptor_Fissure
 - Descriptor_Flat-topped
 - Descriptor_Gray
 - Descriptor_Hair Patch
 - Descriptor_Hyperkeratotic plaques
 - Descriptor_Induration
 - Descriptor_Lichenification
 - Descriptor_Macule
 - Descriptor_Nodule
 - Descriptor_Papule
 - Descriptor_Patch
 - Descriptor_Pedunculated
 - Descriptor_Pigmented
 - Descriptor_Pitted Nail
 - Descriptor_Plaque
 - Descriptor_Poikiloderma
 - Descriptor_Purpura/Petechiae
 - Descriptor_Pustule
 - Descriptor_Salmon
 - Descriptor_Scale
 - Descriptor_Scar
 - Descriptor_Striae
 - Descriptor_Telangiectasia
 - Descriptor_Ulcer
 - Descriptor_Vesicle
 - Descriptor_Warty
 - Descriptor_Wheal
 - Descriptor_White (Hypopigmentation)
 - Descriptor_Xerosis
 - Descriptor_Yellow
 - Confidence
 - Disease_label
 - Fitzpatrick
 - Gradability
 - Image_name
 - Main_class
 - Monk_skin_tone
 - Quality
 - Sex
 - Sub_class
 - Subject_ID

First 5 rows:

,Age,Body_part_Armpits (Axillary Region),Body_part_Back,Body_part_Back of the Knees (Popliteal Region),Body_part_Breasts (Mammary Region),Body_part_Calves (Sural Region),Body_part_Genital Area (Pubic Region),Body_part_Groin (Inguinal Region),Body_part_Head Cheeks,Body_part_Head Chin,...,Disease_label,Fitzpatrick,Gradability,Image_name,Main_class,Monk_skin_tone,Quality,Sex,Sub_class,Subject_ID
0,20 - 40,0,0,0,0,0,0,0,0,1,...,Tinea Faciei,FST 4,Yes,IMG_0017.jpg,Infectious Disorders,MST 7,"Yes, the quality is sufficient for me or anoth...",Male,Infectious skin conditions -Fungal,SUB00004
1,20 - 40,0,0,0,0,0,0,0,0,1,...,Tinea Faciei,FST 4,Yes,IMG_0019.jpg,Infectious Disorders,MST 6,"Yes, the quality is sufficient for me or anoth...",Male,Infectious skin conditions -Fungal,SUB00004
2,40 - 60,0,0,0,1,0,0,0,0,0,...,Pruritic dermatitis,FST 4,Yes,IMG_0044.jpg,Inflammatory Disorders,MST 6,"Yes, the quality is sufficient for me or anoth...",Female,Inflammatory skin diseases (Eczema and Dermati...,SUB00008
3,20 - 40,0,0,0,0,0,0,0,0,0,...,Cheilitis,FST 4,Yes,IMG_0084.jpg,Other skin disorders,MST 6,"Yes, the quality is sufficient for me or anoth...",Male,Other skin disorders,SUB00020
4,40 - 60,0,0,0,0,0,0,0,1,0,...,Tinea Faciei,FST 4,Yes,IMG_0087.jpg,Infectious Disorders,MST 7,"Yes, the quality is sufficient for me or anoth...",Female,Infectious skin conditions -Fungal,SUB00021

In [11]:
# ============================================================
# STEP 11 — DermaCon train/test split validation
# ============================================================

train_path = metadata_root / "train_split-1.csv"
test_path = metadata_root / "test_split-1.csv"

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# ------------------------------------------------------------
# 1. Cancer class counts
# ------------------------------------------------------------

target_keywords = {
    "Melanoma": "melanoma",
    "BCC": "basal cell carcinoma",
    "SCC": "squamous cell carcinoma",
    "MCC": "merkel"
}

print("=" * 70)
print("CANCER COUNTS")
print("=" * 70)

for class_name, keyword in target_keywords.items():

    train_count = train_df["Disease_label"].astype(str).str.lower().str.contains(
        keyword, regex=False
    ).sum()

    test_count = test_df["Disease_label"].astype(str).str.lower().str.contains(
        keyword, regex=False
    ).sum()

    print(f"{class_name:10s} | Train: {train_count:4d} | Test: {test_count:4d}")


# ------------------------------------------------------------
# 2. Subject-level leakage check
# ------------------------------------------------------------

train_subjects = set(train_df["Subject_ID"].astype(str))
test_subjects = set(test_df["Subject_ID"].astype(str))

overlap_subjects = train_subjects.intersection(test_subjects)

print("\n" + "=" * 70)
print("SUBJECT-LEVEL LEAKAGE CHECK")
print("=" * 70)

print("Unique train subjects:", len(train_subjects))
print("Unique test subjects :", len(test_subjects))
print("Subjects in BOTH     :", len(overlap_subjects))

if len(overlap_subjects) == 0:
    print("✅ No Subject_ID overlap between train and test.")
else:
    print("⚠️ Subject_ID overlap detected.")


# ------------------------------------------------------------
# 3. Show overlapping subjects if any
# ------------------------------------------------------------

if len(overlap_subjects) > 0:
    print("\nOverlapping Subject_IDs:")
    print(sorted(list(overlap_subjects))[:50])

======================================================================
CANCER COUNTS
======================================================================
Melanoma   | Train:    2 | Test:    0
BCC        | Train:    6 | Test:    4
SCC        | Train:    3 | Test:    2
MCC        | Train:    0 | Test:    0

======================================================================
SUBJECT-LEVEL LEAKAGE CHECK
======================================================================
Unique train subjects: 2396
Unique test subjects : 606
Subjects in BOTH     : 0
✅ No Subject_ID overlap between train and test.

In [12]:
# ============================================================
# STEP 12 — Inspect DermaCon DATASET_1
# ============================================================

dataset1_root = dermacon_root / "DATASET" / "DATASET_1"

print("=" * 70)
print("DERMACON DATASET_1")
print("=" * 70)

if dataset1_root.exists():
    print("Path:", dataset1_root)

    items = list(dataset1_root.iterdir())

    print("Number of direct items:", len(items))

    for item in items[:30]:
        if item.is_dir():
            print("[FOLDER]", item.name)
        else:
            print("[FILE]  ", item.name)

else:
    print("❌ DATASET_1 path not found:")
    print(dataset1_root)

NameError: name 'dermacon_root' is not defined

In [13]:
from pathlib import Path

dermacon_root = Path("/kaggle/input/datasets/abhig888/dermacon-in")
dataset1_root = dermacon_root / "DATASET" / "DATASET_1"

print("=" * 70)
print("DERMACON DATASET_1")
print("=" * 70)

print("Path:", dataset1_root)
print("Exists:", dataset1_root.exists())

if dataset1_root.exists():
    items = list(dataset1_root.iterdir())

    print("Number of direct items:", len(items))
    print()

    for item in items[:30]:
        if item.is_dir():
            print("[FOLDER]", item.name)
        else:
            print("[FILE]  ", item.name)
else:
    print("❌ DATASET_1 path not found")

======================================================================
DERMACON DATASET_1
======================================================================
Path: /kaggle/input/datasets/abhig888/dermacon-in/DATASET/DATASET_1
Exists: True
Number of direct items: 1

[FOLDER] DATASET_1

In [14]:
# ============================================================
# STEP 13 — Inspect nested DATASET_1
# ============================================================

nested_root = dataset1_root / "DATASET_1"

print("=" * 70)
print("NESTED DATASET_1")
print("=" * 70)

print("Path:", nested_root)
print("Exists:", nested_root.exists())

if nested_root.exists():
    items = list(nested_root.iterdir())

    print("Number of direct items:", len(items))
    print()

    for item in items[:50]:
        if item.is_dir():
            print("[FOLDER]", item.name)
        else:
            print("[FILE]  ", item.name)
else:
    print("❌ Nested DATASET_1 not found")

======================================================================
NESTED DATASET_1
======================================================================
Path: /kaggle/input/datasets/abhig888/dermacon-in/DATASET/DATASET_1/DATASET_1
Exists: True
Number of direct items: 2824

[FILE]   IMG_E3472_2.jpg
[FILE]   IMG_20240214_120444_1.jpg
[FILE]   IMG_20230713_135805_1.jpg
[FILE]   IMG_9304_1.jpg
[FILE]   IMG_9816_1.jpg
[FILE]   IMG_8939_1.jpg
[FILE]   IMG_20240614_120217_1.jpg
[FILE]   IMG20240927105354.jpg
[FILE]   IMG_6574_1.jpg
[FILE]   IMG20241114120454.jpg
[FILE]   IMG_6037_1.jpg
[FILE]   IMG_7625_1.jpg
[FILE]   IMG_7052_1.jpg
[FILE]   IMG20241019123243.jpg
[FILE]   IMG_20230819_145056_1_1_1.jpg
[FILE]   IMG_20230322_191559_1.jpg
[FILE]   IMG_8327.jpg
[FILE]   IMG_20230117_194959_1.jpg
[FILE]   IMG_20231128_200635_1.jpg
[FILE]   IMG_20221212_194232_1_1.jpg
[FILE]   IMG_20230103_132727_1_1.jpg
[FILE]   IMG20240927163049.jpg
[FILE]   IMG_9397_1.jpg
[FILE]   IMG_20230703_150633_1.jpg
[FILE]   IMG_20230614_122246_1.jpg
[FILE]   IMG_7790_1.jpg
[FILE]   IMG_7947.jpg
[FILE]   IMG_20240214_115923_1.jpg
[FILE]   IMG_9037_1.jpg
[FILE]   IMG_9873.jpg
[FILE]   IMG_20230301_150224_1.jpg
[FILE]   IMG_20230117_134215_1.jpg
[FILE]   IMG_20240214_115931_1.jpg
[FILE]   IMG20240716161409.jpg
[FILE]   IMG_20240516_195711_1.jpg
[FILE]   IMG20241220161710.jpg
[FILE]   IMG_7759_2.jpg
[FILE]   IMG_6301_1.jpg
[FILE]   IMG_8242_1.jpg
[FILE]   IMG_8834_1.jpg
[FILE]   IMG20240705125445_1.jpg
[FILE]   IMG_6175_1.jpg
[FILE]   IMG_20230315_124237_1.jpg
[FILE]   IMG_8377_1.jpg
[FILE]   IMG_7665_1.jpg
[FILE]   IMG20240511110747.jpg
[FILE]   IMG20240531153408.jpg
[FILE]   IMG_8427_1.jpg
[FILE]   IMG_20191016_183616_1.jpg
[FILE]   IMG_20231031_130631_2.jpg

In [15]:
# ============================================================
# STEP 14 — Match DATASET_1 images with DermaCon metadata
# ============================================================

import pandas as pd
from pathlib import Path

metadata_file = dermacon_root / "METADATA" / "Skin_Metadata-1.csv"

meta = pd.read_csv(metadata_file)

# Image names from DATASET_1
image_files = [
    p for p in nested_root.iterdir()
    if p.is_file() and p.suffix.lower() in [".jpg", ".jpeg", ".png"]
]

image_names = {p.name.lower() for p in image_files}

# Metadata image names
meta["Image_name_clean"] = (
    meta["Image_name"]
    .astype(str)
    .str.strip()
    .str.lower()
)

matched = meta[meta["Image_name_clean"].isin(image_names)].copy()

print("=" * 70)
print("DATASET_1 ↔ METADATA MATCHING")
print("=" * 70)

print("DATASET_1 image files :", len(image_files))
print("Metadata total rows   :", len(meta))
print("Matched metadata rows :", len(matched))

print("\n" + "=" * 70)
print("CANCER LABELS AMONG MATCHED IMAGES")
print("=" * 70)

cancer_keywords = {
    "Melanoma": "melanoma",
    "BCC": "basal cell carcinoma",
    "SCC": "squamous cell carcinoma",
    "MCC": "merkel"
}

for class_name, keyword in cancer_keywords.items():
    count = matched["Disease_label"].astype(str).str.lower().str.contains(
        keyword, regex=False
    ).sum()
    print(f"{class_name:10s}: {count}")

print("\n" + "=" * 70)
print("SAMPLE MATCHED LABELS")
print("=" * 70)

if len(matched) > 0:
    print(
        matched[["Image_name", "Disease_label"]]
        .head(20)
        .to_string(index=False)
    )
else:
    print("❌ No metadata matches found.")

======================================================================
DATASET_1 ↔ METADATA MATCHING
======================================================================
DATASET_1 image files : 2824
Metadata total rows   : 5450
Matched metadata rows : 2824

======================================================================
CANCER LABELS AMONG MATCHED IMAGES
======================================================================
Melanoma  : 0
BCC       : 9
SCC       : 3
MCC       : 0

======================================================================
SAMPLE MATCHED LABELS
======================================================================
               Image_name           Disease_label
  IMG_20190503_210009.jpg              Hemangioma
  IMG_20190506_200330.jpg                Furuncle
  IMG_20190508_192238.jpg             Acrochordon
  IMG_20190508_193612.jpg             Acrochordon
  IMG_20190511_181817.jpg               Psoriasis
  IMG_20190511_181852.jpg               Psoriasis
IMG_20190614_182343_1.jpg         Photodermatitis
IMG_20190614_182352_1.jpg         Photodermatitis
IMG_20190614_182401_2.jpg         Photodermatitis
IMG_20190706_191716_1.jpg           Herpes Zoster
  IMG_20190709_104403.jpg              Hemangioma
  IMG_20190712_105158.jpg Squamous Cell Carcinoma
  IMG_20190716_182650.jpg   Cutaneous amyloidosis
  IMG_20190716_201400.jpg           Herpes Zoster
  IMG_20190722_184924.jpg                Vitiligo
IMG_20190816_122607_1.jpg Squamous Cell Carcinoma
  IMG_20190909_114946.jpg                  Eczema
  IMG_20190918_104807.jpg    Linear Lichen Planus
IMG_20190918_114747_2.jpg                    Acne
IMG_20190918_114754_1.jpg                    Acne

In [16]:
# ============================================================
# STEP 15 — Inspect 2nd DermaCon Dataset
# ============================================================

from pathlib import Path

dermacon2_root = Path("/kaggle/input/datasets/hiro002/dermacon-in-dataset")

print("=" * 70)
print("DERMACON-IN-DATASET")
print("=" * 70)

print("Path:", dermacon2_root)
print("Exists:", dermacon2_root.exists())

if dermacon2_root.exists():
    items = list(dermacon2_root.iterdir())

    print("Number of direct items:", len(items))
    print()

    for item in items[:50]:
        if item.is_dir():
            print("[FOLDER]", item.name)
        else:
            print("[FILE]  ", item.name)
else:
    print("❌ Dataset path not found")

======================================================================
DERMACON-IN-DATASET
======================================================================
Path: /kaggle/input/datasets/hiro002/dermacon-in-dataset
Exists: True
Number of direct items: 11

[FOLDER] METADATA
[FILE]   train_CBM_SC_MC_type2.py
[FILE]   Infer_Swin_MC.ipynb
[FOLDER] DATASET
[FOLDER] checkpoints
[FILE]   Infer_CBM_MC.ipynb
[FILE]   README.md
[FILE]   train_CBM_SC_MC_type1.py
[FILE]   train_cbm_mc.py
[FILE]   Metadata_schema.md
[FILE]   train_swin_mc.py

In [17]:
# ============================================================
# STEP 16 — Inspect 2nd DermaCon DATASET
# ============================================================

dataset2_root = dermacon2_root / "DATASET"

print("=" * 70)
print("DERMACON-IN-DATASET / DATASET")
print("=" * 70)

print("Path:", dataset2_root)
print("Exists:", dataset2_root.exists())

if dataset2_root.exists():
    items = list(dataset2_root.iterdir())

    print("Number of direct items:", len(items))
    print()

    for item in items[:50]:
        if item.is_dir():
            print("[FOLDER]", item.name)
        else:
            print("[FILE]  ", item.name)
else:
    print("❌ DATASET folder not found")

======================================================================
DERMACON-IN-DATASET / DATASET
======================================================================
Path: /kaggle/input/datasets/hiro002/dermacon-in-dataset/DATASET
Exists: True
Number of direct items: 2

[FOLDER] DATASET_0
[FOLDER] DATASET_1

In [18]:
# ============================================================
# STEP 17 — Inspect DATASET_0 and DATASET_1
# ============================================================

dataset0_root = dataset2_root / "DATASET_0"
dataset1_root_2 = dataset2_root / "DATASET_1"

print("=" * 70)
print("DATASET_0")
print("=" * 70)

if dataset0_root.exists():
    items0 = list(dataset0_root.iterdir())
    print("Direct items:", len(items0))

    for item in items0[:30]:
        print("[FOLDER]" if item.is_dir() else "[FILE]  ", item.name)
else:
    print("❌ DATASET_0 not found")

print("\n" + "=" * 70)
print("DATASET_1")
print("=" * 70)

if dataset1_root_2.exists():
    items1 = list(dataset1_root_2.iterdir())
    print("Direct items:", len(items1))

    for item in items1[:30]:
        print("[FOLDER]" if item.is_dir() else "[FILE]  ", item.name)
else:
    print("❌ DATASET_1 not found")

======================================================================
DATASET_0
======================================================================
Direct items: 1
[FOLDER] DATASET_0

======================================================================
DATASET_1
======================================================================
Direct items: 1
[FOLDER] DATASET_1

In [19]:
# ============================================================
# STEP 18 — Audit all 8 datasets for the 4 cancer types
# ============================================================

from pathlib import Path
import pandas as pd
import re

DATASET_PATHS = {
    "DermaCon-IN-1":
        Path("/kaggle/input/datasets/abhig888/dermacon-in"),

    "DermaCon-IN-2":
        Path("/kaggle/input/datasets/hiro002/dermacon-in-dataset"),

    "ISIC-labelled":
        Path("/kaggle/input/datasets/riyaelizashaju/isic-skin-disease-image-dataset-labelled"),

    "MCC-Dataset":
        Path("/kaggle/input/datasets/quantumcoders05/mcc-dataset"),

    "Skin-Cancer-9":
        Path("/kaggle/input/datasets/nodoubttome/skin-cancer9-classesisic"),

    "HAM10000":
        Path("/kaggle/input/datasets/kmader/skin-cancer-mnist-ham10000"),

    "Skin-DS":
        Path("/kaggle/input/datasets/ahmedxc4/skin-ds"),

    "All-ISIC":
        Path("/kaggle/input/datasets/tomooinubushi/all-isic-data-20240629")
}

TARGET_PATTERNS = {
    "Melanoma": [
        "melanoma",
        "mel"
    ],
    "BCC": [
        "basal cell carcinoma",
        "basal-cell carcinoma",
        "basalcell",
        "basal cell",
        "bcc"
    ],
    "SCC": [
        "squamous cell carcinoma",
        "squamous-cell carcinoma",
        "squamous cell",
        "scc",
        "akiec"
    ],
    "MCC": [
        "merkel cell carcinoma",
        "merkel-cell carcinoma",
        "merkel cell",
        "merkel",
        "mcc"
    ]
}

def detect_cancer_label(text):
    text = str(text).lower().strip()

    # Check more specific names first
    if "merkel" in text:
        return "MCC"

    if "basal cell" in text or "basalcell" in text:
        return "BCC"

    if "squamous cell" in text or "squamous-cell" in text:
        return "SCC"

    if "melanoma" in text:
        return "Melanoma"

    # Common abbreviated labels
    if text in ["mel"]:
        return "Melanoma"

    if text in ["bcc"]:
        return "BCC"

    if text in ["scc", "akiec"]:
        return "SCC"

    if text in ["mcc", "merkel"]:
        return "MCC"

    return None


# ------------------------------------------------------------
# Scan CSV metadata files
# ------------------------------------------------------------

results = []

for dataset_name, root in DATASET_PATHS.items():

    print("\n" + "=" * 70)
    print(dataset_name)
    print("=" * 70)
    print("Path:", root)
    print("Exists:", root.exists())

    if not root.exists():
        print("❌ Dataset not found")
        continue

    csv_files = list(root.rglob("*.csv"))

    print("CSV files found:", len(csv_files))

    dataset_counts = {
        "Melanoma": 0,
        "BCC": 0,
        "SCC": 0,
        "MCC": 0
    }

    for csv_path in csv_files:

        try:
            temp = pd.read_csv(csv_path, low_memory=False)
        except Exception:
            continue

        for col in temp.columns:

            # Only inspect columns likely to contain labels
            col_lower = str(col).lower()

            if any(x in col_lower for x in [
                "diagn", "disease", "label", "class", "dx"
            ]):

                values = temp[col].dropna().astype(str)

                for value in values:
                    detected = detect_cancer_label(value)

                    if detected:
                        dataset_counts[detected] += 1

    print("Melanoma :", dataset_counts["Melanoma"])
    print("BCC      :", dataset_counts["BCC"])
    print("SCC      :", dataset_counts["SCC"])
    print("MCC      :", dataset_counts["MCC"])

    results.append({
        "Dataset": dataset_name,
        "Melanoma": dataset_counts["Melanoma"],
        "BCC": dataset_counts["BCC"],
        "SCC": dataset_counts["SCC"],
        "MCC": dataset_counts["MCC"]
    })


# ------------------------------------------------------------
# Final summary
# ------------------------------------------------------------

summary = pd.DataFrame(results)

print("\n" + "=" * 70)
print("FINAL TYPE DATASET AUDIT")
print("=" * 70)

display(summary)

======================================================================
DermaCon-IN-1
======================================================================
Path: /kaggle/input/datasets/abhig888/dermacon-in
Exists: True
CSV files found: 3
Melanoma : 4
BCC      : 20
SCC      : 10
MCC      : 0

======================================================================
DermaCon-IN-2
======================================================================
Path: /kaggle/input/datasets/hiro002/dermacon-in-dataset
Exists: True
CSV files found: 3
Melanoma : 4
BCC      : 19
SCC      : 11
MCC      : 0

======================================================================
ISIC-labelled
======================================================================
Path: /kaggle/input/datasets/riyaelizashaju/isic-skin-disease-image-dataset-labelled
Exists: True
CSV files found: 0
Melanoma : 0
BCC      : 0
SCC      : 0
MCC      : 0

======================================================================
MCC-Dataset
======================================================================
Path: /kaggle/input/datasets/quantumcoders05/mcc-dataset
Exists: False
❌ Dataset not found

======================================================================
Skin-Cancer-9
======================================================================
Path: /kaggle/input/datasets/nodoubttome/skin-cancer9-classesisic
Exists: True
CSV files found: 0
Melanoma : 0
BCC      : 0
SCC      : 0
MCC      : 0

======================================================================
HAM10000
======================================================================
Path: /kaggle/input/datasets/kmader/skin-cancer-mnist-ham10000
Exists: True
CSV files found: 5
Melanoma : 1113
BCC      : 514
SCC      : 327
MCC      : 0

======================================================================
Skin-DS
======================================================================
Path: /kaggle/input/datasets/ahmedxc4/skin-ds
Exists: True
CSV files found: 0
Melanoma : 0
BCC      : 0
SCC      : 0
MCC      : 0

======================================================================
All-ISIC
======================================================================
Path: /kaggle/input/datasets/tomooinubushi/all-isic-data-20240629
Exists: True
CSV files found: 1
Melanoma : 8465
BCC      : 4921
SCC      : 1372
MCC      : 0

======================================================================
FINAL TYPE DATASET AUDIT
======================================================================

         Dataset  Melanoma   BCC   SCC  MCC
0  DermaCon-IN-1         4    20    10    0
1  DermaCon-IN-2         4    19    11    0
2  ISIC-labelled         0     0     0    0
3  Skin-Cancer-9         0     0     0    0
4       HAM10000      1113   514   327    0
5        Skin-DS         0     0     0    0
6       All-ISIC      8465  4921  1372    0

In [20]:
from pathlib import Path
import pandas as pd
import re

DATASET_PATHS = {
    "DermaCon-IN-1": Path("/kaggle/input/datasets/abhig888/dermacon-in"),
    "DermaCon-IN-2": Path("/kaggle/input/datasets/hiro002/dermacon-in-dataset"),
    "ISIC-labelled": Path("/kaggle/input/datasets/riyaelizashaju/isic-skin-disease-image-dataset-labelled"),
    "MCC-Dataset": Path("/kaggle/input/datasets/quantumcoders04/mcc-dataset"),
    "Skin-Cancer-9": Path("/kaggle/input/datasets/nodoubttome/skin-cancer9-classesisic"),
    "HAM10000": Path("/kaggle/input/datasets/kmader/skin-cancer-mnist-ham10000"),
    "Skin-DS": Path("/kaggle/input/datasets/ahmedxc4/skin-ds"),
    "All-ISIC": Path("/kaggle/input/datasets/tomooinubushi/all-isic-data-20240629")
}

def detect_cancer_label(value):
    if pd.isna(value):
        return None

    s = str(value).strip().lower()

    # MCC
    if (
        "merkel cell" in s
        or "merkel-cell" in s
        or "merkelcell" in s
        or s == "mcc"
        or "mcc" in s
    ):
        return "MCC"

    # BCC
    if (
        "basal cell" in s
        or "basal-cell" in s
        or "basalcell" in s
        or s == "bcc"
    ):
        return "BCC"

    # SCC
    if (
        "squamous cell" in s
        or "squamous-cell" in s
        or "squamouscell" in s
        or s == "scc"
        or "actinic keratos" in s
        or "bowen" in s
    ):
        return "SCC"

    # Melanoma
    if "melanoma" in s or s == "mel":
        return "Melanoma"

    return None


def find_csv_files(root):
    if not root.exists():
        return []
    return list(root.rglob("*.csv"))


final_results = []

for dataset_name, root in DATASET_PATHS.items():

    print("\n" + "=" * 70)
    print(dataset_name)
    print("=" * 70)
    print("Path:", root)
    print("Exists:", root.exists())

    if not root.exists():
        print("❌ Dataset not found")
        final_results.append({
            "Dataset": dataset_name,
            "Melanoma": 0,
            "BCC": 0,
            "SCC": 0,
            "MCC": 0
        })
        continue

    csv_files = find_csv_files(root)
    print("CSV files found:", len(csv_files))

    counts = {
        "Melanoma": 0,
        "BCC": 0,
        "SCC": 0,
        "MCC": 0
    }

    # Scan CSV files
    for csv_path in csv_files:
        try:
            df = pd.read_csv(csv_path, low_memory=False)

            for col in df.columns:

                # Only likely label/diagnosis columns
                col_lower = str(col).lower()

                if not any(k in col_lower for k in [
                    "label", "diagnos", "disease", "class",
                    "target", "type", "condition"
                ]):
                    continue

                for value in df[col].dropna():
                    cancer = detect_cancer_label(value)

                    if cancer is not None:
                        counts[cancer] += 1

        except Exception as e:
            print("⚠️ Could not read:", csv_path.name)
            print("   Error:", str(e)[:150])

    # Also inspect folder names for datasets without CSV
    for img_path in root.rglob("*"):
        if img_path.is_file():
            parts = [p.lower() for p in img_path.parts]

            joined = " ".join(parts)

            cancer = detect_cancer_label(joined)

            if cancer is not None:
                # Folder-based detection is only useful for MCC/private datasets
                # without metadata. We do NOT add these counts here yet.
                pass

    print("Melanoma :", counts["Melanoma"])
    print("BCC      :", counts["BCC"])
    print("SCC      :", counts["SCC"])
    print("MCC      :", counts["MCC"])

    final_results.append({
        "Dataset": dataset_name,
        **counts
    })


# Final table
final_audit = pd.DataFrame(final_results)

print("\n" + "=" * 70)
print("FINAL TYPE DATASET AUDIT")
print("=" * 70)

display(final_audit)

======================================================================
DermaCon-IN-1
======================================================================
Path: /kaggle/input/datasets/abhig888/dermacon-in
Exists: True
CSV files found: 3
Melanoma : 4
BCC      : 20
SCC      : 12
MCC      : 0

======================================================================
DermaCon-IN-2
======================================================================
Path: /kaggle/input/datasets/hiro002/dermacon-in-dataset
Exists: True
CSV files found: 3
Melanoma : 4
BCC      : 19
SCC      : 13
MCC      : 0

======================================================================
ISIC-labelled
======================================================================
Path: /kaggle/input/datasets/riyaelizashaju/isic-skin-disease-image-dataset-labelled
Exists: True
CSV files found: 0
Melanoma : 0
BCC      : 0
SCC      : 0
MCC      : 0

======================================================================
MCC-Dataset
======================================================================
Path: /kaggle/input/datasets/quantumcoders04/mcc-dataset
Exists: True
CSV files found: 0
Melanoma : 0
BCC      : 0
SCC      : 0
MCC      : 0

======================================================================
Skin-Cancer-9
======================================================================
Path: /kaggle/input/datasets/nodoubttome/skin-cancer9-classesisic
Exists: True
CSV files found: 0
Melanoma : 0
BCC      : 0
SCC      : 0
MCC      : 0

======================================================================
HAM10000
======================================================================
Path: /kaggle/input/datasets/kmader/skin-cancer-mnist-ham10000
Exists: True
CSV files found: 5
Melanoma : 0
BCC      : 0
SCC      : 0
MCC      : 0

======================================================================
Skin-DS
======================================================================
Path: /kaggle/input/datasets/ahmedxc4/skin-ds
Exists: True
CSV files found: 0
Melanoma : 0
BCC      : 0
SCC      : 0
MCC      : 0

======================================================================
All-ISIC
======================================================================
Path: /kaggle/input/datasets/tomooinubushi/all-isic-data-20240629
Exists: True
CSV files found: 1
Melanoma : 8673
BCC      : 4921
SCC      : 2739
MCC      : 0

======================================================================
FINAL TYPE DATASET AUDIT
======================================================================

         Dataset  Melanoma   BCC   SCC  MCC
0  DermaCon-IN-1         4    20    12    0
1  DermaCon-IN-2         4    19    13    0
2  ISIC-labelled         0     0     0    0
3    MCC-Dataset         0     0     0    0
4  Skin-Cancer-9         0     0     0    0
5       HAM10000         0     0     0    0
6        Skin-DS         0     0     0    0
7       All-ISIC      8673  4921  2739    0

In [21]:
# ============================================================
# STEP 19 — Verify exact cancer labels in important datasets
# ============================================================

from pathlib import Path
import pandas as pd

CHECK_DATASETS = {
    "HAM10000":
        Path("/kaggle/input/datasets/kmader/skin-cancer-mnist-ham10000"),

    "All-ISIC":
        Path("/kaggle/input/datasets/tomooinubushi/all-isic-data-20240629"),

    "MCC-Dataset":
        Path("/kaggle/input/datasets/quantumcoders04/mcc-dataset"),

    "Skin-Cancer-9":
        Path("/kaggle/input/datasets/nodoubttome/skin-cancer9-classesisic"),

    "Skin-DS":
        Path("/kaggle/input/datasets/ahmedxc4/skin-ds"),

    "ISIC-labelled":
        Path("/kaggle/input/datasets/riyaelizashaju/isic-skin-disease-image-dataset-labelled")
}


# ------------------------------------------------------------
# 1. HAM10000 exact label distribution
# ------------------------------------------------------------

print("=" * 70)
print("HAM10000 — EXACT LABEL CHECK")
print("=" * 70)

ham_root = CHECK_DATASETS["HAM10000"]

for csv_file in ham_root.rglob("*.csv"):

    try:
        df = pd.read_csv(csv_file, low_memory=False)
    except:
        continue

    print("\nCSV:", csv_file.name)
    print("Columns:", list(df.columns))

    for col in df.columns:

        if str(col).lower() in [
            "dx",
            "diagnosis",
            "diagnosis_1",
            "disease",
            "label",
            "class"
        ]:

            print("\nLabel column:", col)
            print(df[col].value_counts(dropna=False).head(30))


# ------------------------------------------------------------
# 2. All-ISIC label columns
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("ALL-ISIC — LABEL COLUMN CHECK")
print("=" * 70)

isic_root = CHECK_DATASETS["All-ISIC"]

for csv_file in isic_root.rglob("*.csv"):

    try:
        df = pd.read_csv(csv_file, low_memory=False)
    except:
        continue

    print("\nCSV:", csv_file.name)
    print("Shape:", df.shape)
    print("Columns:")
    print(list(df.columns))

    for col in df.columns:

        col_lower = str(col).lower()

        if any(x in col_lower for x in [
            "dx",
            "diagnos",
            "disease",
            "label",
            "class"
        ]):

            print("\nPossible label column:", col)
            print(df[col].value_counts(dropna=False).head(30))


# ------------------------------------------------------------
# 3. MCC DATASET — folder structure
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("MCC-DATASET — FOLDER STRUCTURE")
print("=" * 70)

mcc_root = CHECK_DATASETS["MCC-Dataset"]

print("Path:", mcc_root)
print("Exists:", mcc_root.exists())

if mcc_root.exists():

    all_items = list(mcc_root.rglob("*"))

    folders = [p for p in all_items if p.is_dir()]
    files = [p for p in all_items if p.is_file()]

    print("Total folders:", len(folders))
    print("Total files :", len(files))

    print("\nFolders:")
    for p in folders[:100]:
        print("[FOLDER]", p.relative_to(mcc_root))

    print("\nFirst 50 files:")
    for p in files[:50]:
        print("[FILE]", p.relative_to(mcc_root))


# ------------------------------------------------------------
# 4. Other two datasets — structure
# ------------------------------------------------------------

for dataset_name in ["Skin-Cancer-9", "Skin-DS", "ISIC-labelled"]:

    root = CHECK_DATASETS[dataset_name]

    print("\n" + "=" * 70)
    print(dataset_name)
    print("=" * 70)

    print("Path:", root)
    print("Exists:", root.exists())

    if root.exists():

        items = list(root.rglob("*"))

        folders = [p for p in items if p.is_dir()]
        files = [p for p in items if p.is_file()]

        print("Folders:", len(folders))
        print("Files  :", len(files))

        print("\nTop-level items:")

        for p in list(root.iterdir())[:50]:
            print(
                "[FOLDER]" if p.is_dir() else "[FILE]  ",
                p.name
            )

======================================================================
HAM10000 — EXACT LABEL CHECK
======================================================================

CSV: hmnist_8_8_RGB.csv
Columns: ['pixel0000', 'pixel0001', 'pixel0002', 'pixel0003', 'pixel0004', 'pixel0005', 'pixel0006', 'pixel0007', 'pixel0008', 'pixel0009', 'pixel0010', 'pixel0011', 'pixel0012', 'pixel0013', 'pixel0014', 'pixel0015', 'pixel0016', 'pixel0017', 'pixel0018', 'pixel0019', 'pixel0020', 'pixel0021', 'pixel0022', 'pixel0023', 'pixel0024', 'pixel0025', 'pixel0026', 'pixel0027', 'pixel0028', 'pixel0029', 'pixel0030', 'pixel0031', 'pixel0032', 'pixel0033', 'pixel0034', 'pixel0035', 'pixel0036', 'pixel0037', 'pixel0038', 'pixel0039', 'pixel0040', 'pixel0041', 'pixel0042', 'pixel0043', 'pixel0044', 'pixel0045', 'pixel0046', 'pixel0047', 'pixel0048', 'pixel0049', 'pixel0050', 'pixel0051', 'pixel0052', 'pixel0053', 'pixel0054', 'pixel0055', 'pixel0056', 'pixel0057', 'pixel0058', 'pixel0059', 'pixel0060', 'pixel0061', 'pixel0062', 'pixel0063', 'pixel0064', 'pixel0065', 'pixel0066', 'pixel0067', 'pixel0068', 'pixel0069', 'pixel0070', 'pixel0071', 'pixel0072', 'pixel0073', 'pixel0074', 'pixel0075', 'pixel0076', 'pixel0077', 'pixel0078', 'pixel0079', 'pixel0080', 'pixel0081', 'pixel0082', 'pixel0083', 'pixel0084', 'pixel0085', 'pixel0086', 'pixel0087', 'pixel0088', 'pixel0089', 'pixel0090', 'pixel0091', 'pixel0092', 'pixel0093', 'pixel0094', 'pixel0095', 'pixel0096', 'pixel0097', 'pixel0098', 'pixel0099', 'pixel0100', 'pixel0101', 'pixel0102', 'pixel0103', 'pixel0104', 'pixel0105', 'pixel0106', 'pixel0107', 'pixel0108', 'pixel0109', 'pixel0110', 'pixel0111', 'pixel0112', 'pixel0113', 'pixel0114', 'pixel0115', 'pixel0116', 'pixel0117', 'pixel0118', 'pixel0119', 'pixel0120', 'pixel0121', 'pixel0122', 'pixel0123', 'pixel0124', 'pixel0125', 'pixel0126', 'pixel0127', 'pixel0128', 'pixel0129', 'pixel0130', 'pixel0131', 'pixel0132', 'pixel0133', 'pixel0134', 'pixel0135', 'pixel0136', 'pixel0137', 'pixel0138', 'pixel0139', 'pixel0140', 'pixel0141', 'pixel0142', 'pixel0143', 'pixel0144', 'pixel0145', 'pixel0146', 'pixel0147', 'pixel0148', 'pixel0149', 'pixel0150', 'pixel0151', 'pixel0152', 'pixel0153', 'pixel0154', 'pixel0155', 'pixel0156', 'pixel0157', 'pixel0158', 'pixel0159', 'pixel0160', 'pixel0161', 'pixel0162', 'pixel0163', 'pixel0164', 'pixel0165', 'pixel0166', 'pixel0167', 'pixel0168', 'pixel0169', 'pixel0170', 'pixel0171', 'pixel0172', 'pixel0173', 'pixel0174', 'pixel0175', 'pixel0176', 'pixel0177', 'pixel0178', 'pixel0179', 'pixel0180', 'pixel0181', 'pixel0182', 'pixel0183', 'pixel0184', 'pixel0185', 'pixel0186', 'pixel0187', 'pixel0188', 'pixel0189', 'pixel0190', 'pixel0191', 'label']

Label column: label
label
4    6705
6    1113
2    1099
1     514
0     327
5     142
3     115
Name: count, dtype: int64

CSV: hmnist_28_28_RGB.csv

In [22]:
from pathlib import Path

MCC_ROOT = Path("/kaggle/input/datasets/quantumcoders04/mcc-dataset")

print("=" * 70)
print("MCC DATASET — STRUCTURE CHECK")
print("=" * 70)

print("Exists:", MCC_ROOT.exists())
print("Path:", MCC_ROOT)

if MCC_ROOT.exists():
    print("\nTop-level items:")
    for p in sorted(MCC_ROOT.iterdir()):
        kind = "FOLDER" if p.is_dir() else "FILE"
        print(f"[{kind}] {p.name}")

    images = [
        p for p in MCC_ROOT.rglob("*")
        if p.is_file() and p.suffix.lower() in
        (".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff", ".webp")
    ]

    print("\nTotal image files:", len(images))

    print("\nFirst 30 image paths:")
    for p in images[:30]:
        print(" ", p.relative_to(MCC_ROOT))
else:
    print("ERROR: MCC dataset path does not exist.")

======================================================================
MCC DATASET — STRUCTURE CHECK
======================================================================
Exists: True
Path: /kaggle/input/datasets/quantumcoders04/mcc-dataset

Top-level items:
[FOLDER] mcc image

Total image files: 17

First 30 image paths:
  mcc image/41698_2025_987_Fig1_HTML.webp
  mcc image/imge.jpeg
  mcc image/canvas 1.png
  mcc image/images_large_rg.2019190102.fig2.jpeg
  mcc image/12885_2013_Article_4464_Fig1_HTML.webp
  mcc image/images_g02mr14c1x.jpeg
  mcc image/cancers-16-03586-g001.png
  mcc image/canvas.png
  mcc image/full-1255fig02.jpeg
  mcc image/cancers-16-03586-g002.png
  mcc image/41571_2018_103_Fig1_HTML.jpg
  mcc image/cup13910-fig-0001-m.jpg
  mcc image/canvas 2.png
  mcc image/5cm.webp
  mcc image/12885_2013_Article_4464_Fig3_HTML.webp
  mcc image/cup13910-fig-0001-m - Copy.jpg
  mcc image/images_g02mr14c2x.jpeg